### ISSUE TITLE
Crash when trying to sign-in

### ISSUE THREAD

**Issue by null2264** [ChristopherHX/mcpelauncher-manifest#10]
I'm currently on ElementaryOS Juno (Ubuntu 18.04)
Your linux fork does fixed 1.13.1.5 crash but everytime i tried to login to xbox it's crashed...
It's seems like msa-daemon from your fork doesn't work, i fixed the problem by uninstalling then install the old msa-daemon from mcmrarm's repository.

Update : It is fixed the problem but it wont saved... it keep asking me to sign in, i dont know if that's the problem of using old msa-daemon or not...

**Comment by ChristopherHX** [comment]
I didn't modified anything besides mcpelauncher-client.
The original msa-daemon, msa-ui-qt and mcpelauncher-ui-qt from minecraft-linux aren't different at all.
**"It is fixed the problem but it wont saved" Read my ReadMe.
I switch to my own XBL Patch with no auto login (the previous attempt crashed to much / not worked on MacOs)**

**Comment by null2264** [comment]
Oh i see... i still have no idea of why the msa dont want to launched but i guess everything is fine...
