### ISSUE TITLE
Game uses software rendering even though nvidia graphics is enabled using optimus manager

### ISSUE THREAD

**Issue by ebiak** [ChristopherHX/mcpelauncher-manifest#101]
I am trying run minecraft on arch linux and I am using my nvidia card but minecraft still runs using software rendering, it runs fine on pop os on the same hardware

**Comment by ChristopherHX** [comment]
Are you shure you have installed 32bit nvidia graphics drivers (for Opengl **ES2**) correctly?
Nvidia drivers are for me allways a pain (if it even works)
My download page cannot include third party drivers like nvidia in the instruction.

**Comment by ebiak** [comment]
`glxinfo | grep OpenGL` returns this:
```
OpenGL vendor string: NVIDIA Corporation
OpenGL renderer string: GeForce GT 425M/PCIe/SSE2
OpenGL core profile version string: 4.6.0 NVIDIA 390.132
OpenGL core profile shading language version string: 4.60 NVIDIA
OpenGL core profile context flags: (none)
OpenGL core profile profile mask: core profile
OpenGL core profile extensions:
OpenGL version string: 4.6.0 NVIDIA 390.132
OpenGL shading language version string: 4.60 NVIDIA
OpenGL context flags: (none)
OpenGL profile mask: (none)
OpenGL extensions:
OpenGL ES profile version string: OpenGL ES 3.2 NVIDIA 390.132
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.20
OpenGL ES profile extensions:

```
how can i make sure i have the 32bit nvidia drivers installed?

**Comment by ebiak** [comment]
there is a 32bit driver in the aur i will try that

**Comment by ebiak** [comment]
yes that was it i needed [this](https://aur.archlinux.org/packages/lib32-nvidia-390xx-utils) driver for it to use hardware rendering and it works as good (if not better) as pop os
