### ISSUE TITLE
Xbox live interface completly broken 1.16.0.67+

### ISSUE THREAD

**Issue by ChristopherHX** [ChristopherHX/mcpelauncher-manifest#104]
1.16.0.67+ (beta) switched the xbox live gameinterface to xal. 
Xbox login fails immediatly.
No workaround.

1.16.1.02 not affected

**Comment by kode54** [comment]
Seems to log in when I connect to a server, but I don't know if it's actually connecting. The only sign of it being amiss thus far is that it fails to sync my character profiles on first launch, until I've connected to a server. Then I have to disconnect and reconnect to the server for my profile to show up to other players.

**Comment by ChristopherHX** [comment]
"fails to sync my character",
Mojangs bug https://bugs.mojang.com/browse/MCPE-48207

They may fixed it in https://feedback.minecraft.net/hc/en-us/articles/360045602971-Minecraft-1-16-1-Bedrock- 

I opened this not for poor xboxlive support, but for **absolutly no** Xboxlive support in Coming Releases (1.16.2 or later)

**Comment by ChristopherHX** [comment]
Will work soon in ng, but this repo (my fork) will freeze soon.
https://github.com/minecraft-linux/mcpelauncher-manifest/issues/374#issuecomment-674563699

**Comment by ChristopherHX** [comment]
Implemented in ng
