### ISSUE TITLE
Crash when creating new world in 1.13.1.5 and 1.12.1.1

### ISSUE THREAD

**Issue by Muhajaya** [ChristopherHX/mcpelauncher-manifest#11]
Log in 1.13.1.5 : https://del.dog/dehuyudexa
Log in 1.12.1.1 : https://del.dog/cafemotaju

**Comment by ChristopherHX** [comment]
Currently I know no way to reproduce your Bug.
The log said something like rendering Minecraft isn't working. Maybe some Problems with your Graphics card but I don't know.

**Comment by ChristopherHX** [comment]
I close this now, maybe your operating System or Computer is incompatible with an unknown Reason
