### ISSUE TITLE
Doesn't run spectacularly well.

### ISSUE THREAD

**Issue by TheDood1092** [ChristopherHX/mcpelauncher-manifest#110]
The Frame Rate is choppy, can V-Sync be implemented? Anti-aliasing would also be amazing!! Otherwise it works very well, great job!

**Comment by ChristopherHX** [comment]
no vsync:
Are you on macOS? (then not planned)
Vsync works on linux fine for my intel hd.

**Comment by TheDood1092** [comment]
Very sorry, it turns out it was just a bit sluggish due to behavior packs. Well done on the launcher in general, this is now how I primarily play the game now and I'll be starting a server.
