### ISSUE TITLE
Google Login page way too big

### ISSUE THREAD

**Issue by SYZYGY-DEV333** [ChristopherHX/mcpelauncher-manifest#115]
When I try to login with google, the login window is way bigger than my HD monitor and can't be resized. Is there any way to make it more sensible?

**Comment by ChristopherHX** [comment]
Maybe this helps https://github.com/ChristopherHX/mcpelauncher-ui-manifest/issues/9#issuecomment-643756278

**Comment by SYZYGY-DEV333** [comment]
`QT_AUTO_SCREEN_SCALE_FACTOR=0 ./MC.AppImage` did it. Thanks for the tip!
