### ISSUE TITLE
launcher problebs

### ISSUE THREAD

**Issue by storm106** [ChristopherHX/mcpelauncher-manifest#118]
i have the appimage installed but when I press download and play it does not do anything or when it does it just crashes. I cant figure this one out so can i get help pls.

**Comment by ChristopherHX** [comment]
Please provide the full message of the crash, to get help. _to copy all text of the crash window press the top-right button, below the close button_
Otherwise, I have no idea what doesn't work for you.

**Comment by ChristopherHX** [comment]
Closed, No response
