### ISSUE TITLE
Problems with Launcher

### ISSUE THREAD

**Issue by AtlanticDany** [ChristopherHX/mcpelauncher-manifest#120]
/tmp/.mount_MC.AppEKKmlr/usr/bin/./mcpelauncher-client: error while loading shared libraries: libXext.so.6: cannot open shared object file: No such file or directory

Missing launcher dependencies, please install all missing libraries in their right version

**Comment by ChristopherHX** [comment]
I assume you are using debian like (lack of information) `sudo apt install libxext6:i386` https://packages.debian.org/buster/libxext6

_Download page updated_

**Comment by AtlanticDany** [comment]
Thank you very much, now I try then in case I let you know

**Comment by ChristopherHX** [comment]
I think this can be closed
