### ISSUE TITLE
Where is the worlds folder

### ISSUE THREAD

**Issue by epiixgd76** [ChristopherHX/mcpelauncher-manifest#123]
aaaaaaa where is the worlds folder for installing maps

**Comment by CyberBacon07** [comment]
did you figure it out?

**Comment by chinoto** [comment]
Click on the gear, click "Open GameData Folder", which brings me to `/home/$USER/.var/app/io.mrarm.mcpelauncher/data/mcpelauncher/`, then I navigate further to `./games/com.mojang/minecraftWorlds/`.

**Comment by ChristopherHX** [comment]
> How do you add a world?

- rename myworld.mcworld to myworld.zip
- unzip myworld.zip
- put the extracted folder into minecraftWorlds
- restart the game

You can still do everything wrong and end up not seeing anything.

**Comment by CyberBacon07** [comment]
nvm figured it out
