### ISSUE TITLE
Add build instructions for Arch Linux ARM

### ISSUE THREAD

**Issue by benthetechguy** [ChristopherHX/mcpelauncher-manifest#126]
I run Manjaro on a Raspberry Pi, so for me the build instructions would be somewhere between the Debian ARM instructions and the Arch Linux x86 instructions. I can use the AppImage, but I still can't play because I don't have the right dependencies installed. I don't know how to install them because the Debian ones don't exist in Arch repos and the Arch ones are i686 only. So I don't know what to do here other than use Raspbian on a second SD card.

**Comment by ChristopherHX** [comment]
which Arch Linux ARM?
- Arch Linux ARM **armv7 32bit** OS
  - I have no arch arm32 on my Raspberry Pi**2** so up to you to replace i686 with arm inside the cloned repos 
- Arch Linux ARM **armv8 64bit** OS
  - Bad choice, build from source too complex
     - Missing armv7 32bit multiarch, aarch64 is unsupported
  - flatpak could theoretically work but it have certificate problems on manjaro arm
  - Reconsider your Operating System 
     - go to, you are the 3rd persion with this question https://github.com/minecraft-linux/mcpelauncher-client/issues/12#issuecomment-663147837

**Comment by ChristopherHX** [comment]
archlinux x86_64 works, because it have i686 multiarch libraries.
debian / ubuntu arm64 works, because it have armhf (32bit) multiarch libraries.

**Comment by benthetechguy** [comment]
This issue is no longer relevant since mcpelauncher now supports 64 bit architectures directly without needing multiarch.
