### ISSUE TITLE
minecraft opens loadin screen then crashes (flatpack)

### ISSUE THREAD

**Issue by ErikTheWild555** [ChristopherHX/mcpelauncher-manifest#128]
issue in log to long to post

**Comment by ChristopherHX** [comment]
Copy the log in a log.txt file and upload the textfile to your message (I don't think it is more than 10MB)
Or use a website like https://pastebin.com/

Why I need the log?
- You don't told me which cpu you have
  - There are a lot of amd cpu, which may be to old and lead to a illegal instruction crash short after loading the game.
  - Some cpu's lead to crashes I never saw and maybe Mojangs Bug
- You don't told me which game version you tried to launch
  - Current Beta versions lead to crash
- Maybe really launcher bug
  - It works for me with 1.14 - 1.16.10.02
  - on my pc it is more stable than for an average github issue reporter of this launcher
- In most cases I cannot reproduce the behavior as I don't own a equivalent Machine with that specic OS
  - Therefore might never get fixed.

Disclaimer: I cannot warrent that you will ever be able to play the game on your Device with Linux.

_This laucher will be unable to run 1.16.20+ or at least xbox live multiplayer won't work, this might change later this year_
