### ISSUE TITLE
Strange gmail access after giving google credentials

### ISSUE THREAD

**Issue by ufa** [ChristopherHX/mcpelauncher-manifest#134]
Hi,
I have given my google credentials so the launcher could download the game, but right after that an strange access appeared in myaccount. 
Could you please clarify the Google logon process and why a Samsung S8 logged in my account right after I gave the credentials? Thanks in advance

**Comment by ufa** [comment]
I think it is just a label so the launcher can download the files, but i would like to confirm that behaviour

**Comment by ChristopherHX** [comment]
Because of a bug, people said the device was marked as insecure and google blocked them from login.
Then the useragent from qt was changed to an s8 by a PR.

Feel free to look into mcpelauncher-ui-qt src it is only a useragent of an s8

**Comment by ChristopherHX** [comment]
https://github.com/minecraft-linux/playdl-signin-ui-qt/pull/1

Somehow the launcher needs a google play master token, unencrypted stored on your machine "~/.config/Minecraft Linux Launcher" (linux).
Used to talk with google play, no idea how that works not my code..

**Comment by ufa** [comment]
Thank you

**Comment by Headset100YT** [comment]
hi do for chomebook

**Comment by cronnoz** [comment]
I get Error while extracting the file: Failed to open zip 21 when putting the apk version 1.16.40.2, what should I do?
