### ISSUE TITLE
[macOS] Ok I found a loop hole for the google thing, but now I run into a problem where it says “Could not find the game launcher. Please make sure it’s properly installed etc.”

### ISSUE THREAD

**Issue by Flxdow** [ChristopherHX/mcpelauncher-manifest#139]
Pls help, my discord tag is:       Flxdow#9223

**Comment by Flxdow** [comment]
![65271D0F-C14E-4C3B-A003-A81920250346](https://user-images.githubusercontent.com/66448046/91592219-337ec400-e92c-11ea-9c44-ca9ebb92e0da.jpeg)

**Comment by ChristopherHX** [comment]
please don't open the issue 3times.
This dmg seems outdated

**Comment by ChristopherHX** [comment]
You are on catalina use the second download (ng)
https://github.com/ChristopherHX/mcpelauncher-manifest/releases

**the error message of the screenshot is removed**
