### ISSUE TITLE
Moving on certain worlds crashes the game with exit code 8

### ISSUE THREAD

**Issue by i-use-arch-btw** [ChristopherHX/mcpelauncher-manifest#14]
The specific world can be found here: https://drive.google.com/open?id=1n0GOYAnE5kBB4UyXMa8abJEii0lpvoXX

**Comment by ChristopherHX** [comment]
I suppose you world is corrupted (Minecraft Bug)
What version hash are you on, I suggesting updating (an errorlog contains version information in the first lines).
It's a rolling fork. When and how did you install it?
AUR need reinstallation of mcpelauncher-linux-git for every update
I can move on your world without issues. (Minecraft 1.14.0.9)

Same error code 8 appeared the third time, unknown cause. I had the same issue while testing, but Minecraft Version change maybe fix it itself.

**Comment by i-use-arch-btw** [comment]
1. 20:43:23 Info  [Launcher] Version: client 629f65d / manifest 597b307
2. I installed it using the latest appimage (the one thats using angle to render)

Speaking of world corruption, I suppose I could accept that that is the reason because the world was originally from 1.13.0.34 however when I imported my world to my realms server everything worked fine without issues.

**Comment by ChristopherHX** [comment]
Well the gdb says its an Arithmetic exception (SIGFPE) some PC get it (my i7 8th gen gets it too(Ubuntu 19.04 amd64), but i5 3rd gen on MacOs not)
I'm working on a fix, maybe ignore the signal helps

**Comment by ChristopherHX** [comment]
Ignore it work only outside of gdb still not good, but it seems to work
I will push a fix "workaround" for it

**Comment by ChristopherHX** [comment]
Update ignoring it isn't a Solution, its a really big floating point bug on x86 (not ARM)
Ignoring it causes
- infinite save screen
- World gen aborts
- maybe my ignore method kills mc threads

**Comment by ChristopherHX** [comment]
Try this copy of you world https://drive.google.com/file/d/1fLjgRNyKAQEtgcDfiFhZvGSy0RPpQQXr/view?usp=drivesdk
Minecraft on android fixed it itself

**Comment by ChristopherHX** [comment]
With my latest **Experimental** Patch Minecraft will not crash in your world (Linux only) (you posted, replaced fault by No Operation (0x90) on x86)
**I cannot imagine which side effects this Patch has (only applied if the game would crash and a Warning in the LOG)**

It's workaround is included the latest Appimage https://github.com/ChristopherHX/linux-packaging-scripts/releases/tag/54.appimage

**Comment by i-use-arch-btw** [comment]
It seems to be working fine. Will close this issue for now.
