### ISSUE TITLE
Catalina just wont work! NG

### ISSUE THREAD

**Issue by bli488** [ChristopherHX/mcpelauncher-manifest#140]
@ChristopherHX I need some help when you set out the new version of minecraft bedrock launcher it just not working everytime i down load the dmg for the old one(remember me you sent me that dmg) and open it it updates to the newest version can  you send me a dmg like this https://github.com/ChristopherHX/osx-packaging-scripts/releases/download/ng.dmg/Minecraft_Bedrock_Launcher_0.0.209_macOS_10.13.0.dmg but it it shoud not update to the  newest version

**Comment by ChristopherHX** [comment]
You can press skip this update or close the update window etc..
Then just disable "Enable checking for updates (startup)" in Launcher Settings.

Why should sparkle even show you that a new version is available, on that new Version?
Is it 0.*.168, but isn't that a lower version?
https://github.com/ChristopherHX/osx-packaging-scripts/releases/download/ng.dmg/appcast.xml

**Comment by bli488** [comment]
i have 10.15 on my mac and it wont support it, making the launcher x86_64 bit may be the only solution, is there some way you can do this

**Comment by ChristopherHX** [comment]
I don't get it, what do you expect?
Binaries that are x86_64
- mcpelauncher-client, **since ng, the launcher confirmed to work on 10.15**
- mcpelauncher-ui-qt
- msa-ui-qt
- msa-daemon

Binaries that are i386 mojave exclusive
- mcpelauncher-client, **pre ng**, known as launcher not found on 10.15, last year now x86_64
- mcpelauncher-client32, **since ng**

No I won't remove i386, because
- I'm still on Mojave
- Not all x86_64 pc's can run the x86_64 version of the game, but work with i386
- Can run older game versions on mojave than on Catalina

**Comment by bli488** [comment]
well i ran the trouble shooter and hear what it said

Android app compatibility:

1. arm64-v8a is unsupported not an aarch64 system 
2. armeabi-v8a is unsupported not anarmv7 system
3. x86 is unsupported your macOS doesn't support running x86 (32bit) apps anymore, since macOS catalina 10.15
4. x86_64 is supported

i understand if you do not make it x86_64 or remove i386 but is there some code i can do to help myself?

**Comment by ChristopherHX** [comment]
Disclaimer I'm not a macOS Developer, keeping macOS support is on best effort basis.

`x86_64 is supported` why not using the x86_64 version?
**The launcher is both x86_64 and x86**
x86 support will never change for you if you not switch your OS, apple removed it for you.

Please download the  0.\*.168 version from release page and stick on 1.16.10.\* for now.


1.16.20+ still crashs 80+% of times starting the game on macOS with an unfinished update you downloaded.
**That is the reason why it is not released and the issues are still open**
The same code on Linux crashs less than 5% of times starting the same game.
