### ISSUE TITLE
Launcher window is MASSIVE

### ISSUE THREAD

**Issue by DelxHQ** [ChristopherHX/mcpelauncher-manifest#152]
![Screenshot from 2020-11-16 02-43-21](https://user-images.githubusercontent.com/16628342/99207320-95c1c500-27b5-11eb-8476-1aa029b6a801.png)

Linux Distro: **PopOS**

**Comment by ChristopherHX** [comment]
Duplicate with workaround https://github.com/ChristopherHX/mcpelauncher-ui-manifest/issues/9
