### ISSUE TITLE
Launcher Crashed

### ISSUE THREAD

**Issue by loueljay05** [ChristopherHX/mcpelauncher-manifest#156]
Did older Launcher Versions work on this PC?
```
Yes
```
# Disclaimer
If you don't answer these questions your issue will be closed

**Comment by ChristopherHX** [comment]
Was the errorlog really empty?
Was it the AppImage?
Was it the flatpak?
Was it the macOS dmg?
Output of the Troubleshooter? in settings

If it was the appimage you can you back if you start the file with the same name as the AppImage + `.zs-old`

I cannot help you without a log, I don't even know the problem other than it failed

**Comment by ChristopherHX** [comment]
Invalid and no interest in solving your problem.
