### ISSUE TITLE
Xbox login crash

### ISSUE THREAD

**Issue by TaiKInGithub** [ChristopherHX/mcpelauncher-manifest#158]
I can not connect to xbox I tested with 2 accounts
<img width="507" alt="Capture d’écran 2020-11-24 à 09 41 03" src="https://user-images.githubusercontent.com/47861701/100069553-2f821580-2e39-11eb-823d-af2a5c43de14.png">

**Comment by ChristopherHX** [comment]
On discord some people said login works better with 1.16.40, then open 1.16.100 and you are still signed in.

Which crash? post the log
This screenshot is an error message, which the game shows if it haven't finished xboxlive init takes ca. 30s-7min

**Comment by TaiKInGithub** [comment]
I can get the discord ?

**Comment by ChristopherHX** [comment]
Invite link is here (bottom of the page)
https://mcpelauncher.readthedocs.io/en/latest/getting_started.html#getting-help

**Comment by TaiKInGithub** [comment]
je suis sur le discord pouvez vous m'aidé ?

**Comment by ChristopherHX** [comment]
This isn't a crash at all
