### ISSUE TITLE
Mouse cursor falls off window edge

### ISSUE THREAD

**Issue by ceeeKay** [ChristopherHX/mcpelauncher-manifest#166]
Normally (e.g. in Windows 10) if I'm in-game my mouse cursor is captured such that I can't move off the edge of the window. Only when I hit a menu or something that enables the mouse cursor can I go off the edges.

However, I've found that this seems to be an issue with my combination:

Chromebook HP 14a-na0023cl
Debian Buster installed via "Enable Linux" in ChromeOS
Minecraft 1.16.101.01 (x86_64)
Launcher 0.1.b2-AppImage-x86_64.618

Alternatively, is there a way to set the resolution values such that it launches in a true full screen mode? (e.g. it'd be Alt-Enter on Win10)

Happy to report that this was all it took to get running:

      sudo dpkg --add-architecture i386
      sudo apt-get update
      sudo apt install curl libc6-i386 libx11-6:i386 libxext6:i386 libegl1-mesa:i386 zlib1g:i386 libstdc++6:i386 libgl1-mesa-dri:i386 libasound2:i386 libpulse0:i386
      curl -L https://github.com/ChristopherHX/linux-packaging-scripts/releases/download/appimage/Minecraft_Bedrock_Launcher-x86_64.0.0.540.AppImage --output MC.AppImage
      chmod +x MC.AppImage 
      ./MC.AppImage 

Encountered a launcher crash but once I let it install an update and restart the game launched just fine.

**Comment by ChristopherHX** [comment]
You must allow this app to do what you want, allways allowed on real linux desktop.

Enable this Chrome flag `chrome://flags/#exo-pointer-lock` see here
https://github.com/flathub/io.mrarm.mcpelauncher/issues/8#issuecomment-716827632
and here
https://github.com/ChristopherHX/mcpelauncher-manifest/issues/119#issuecomment-662162874

**Comment by ceeeKay** [comment]
Perfect thanks!
