### ISSUE TITLE
Launcher Crashed

### ISSUE THREAD

**Issue by bientres** [ChristopherHX/mcpelauncher-manifest#170]
Did older Launcher Versions work on this PC?
```
16:03:42 Trace [HybrisUtils] Loaded OS library libz.dylib
16:03:42 Trace [HybrisUtils] Loaded OS library libm.dylib
16:03:42 Trace [HybrisUtils] Loaded OS library /private/var/folders/b5/sgxbn33j4jx7qf2d2dx_jzkm0000gn/T/AppTranslocation/3D614B95-C7B1-441E-8123-A6D64AE70AB4/d/Minecraft Bedrock.app/Contents/Resources/mcpelauncher/lib/native/x86_64/libfmod.dylib
Signal 11 received
Backtrace elements: 8
#0 0   mcpelauncher-client                 0x0000000104aabf92 _ZN12CrashHandler12handleSignalEiPv + 226
#1 1   libsystem_platform.dylib            0x00007fff6f8a0f5a _sigtramp + 26
#2 2   ???                                 0x0000000000000000 0x0 + 0
#3 3   mcpelauncher-client                 0x0000000104a8bbcd _ZN11HookManager7LibInfoC1EPv + 29
#4 4   mcpelauncher-client                 0x0000000104a8c26a _ZN11HookManager10addLibraryEPv + 90
#5 5   mcpelauncher-client                 0x0000000104786633 main + 7571
#6 6   libdyld.dylib                       0x00007fff6f592015 start + 1
#7 7   ???                                 0x0000000000000007 0x0 + 7
Dumping stack...

Process exited with unexpected exit code: 6

```
# Disclaimer
If you don't answer these questions your issue will be closed

**Comment by ChristopherHX** [comment]
You are running an old version of the Launcher, I cannot fix anything if you won't update.
See wiki to update it [Updating the launcher](https://github.com/minecraft-linux/mcpelauncher-wiki/blob/Update-wiki-for-ng/troubleshooting.rst#id1)
Settings about `v0.1b2` is the current version.

Feel free to open a new issue, if you have trouble updating it.

**Comment by ChristopherHX** [comment]
I heard of a potenially tampered Launcher from mediafire

You find offical releases from me on github (https://github.com/ChristopherHX/osx-packaging-scripts/releases/tag/ng.dmg).
They are still unsigned, but it seems to be reasonable to increase secureity.
