### ISSUE TITLE
Launcher crashed

### ISSUE THREAD

**Issue by JKakaofanatiker** [ChristopherHX/mcpelauncher-manifest#175]
Did older Launcher Versions work on this PC?
Yes

`15:56:52 Info  [Launcher] Version: client 666ad06 / manifest 93e2273
15:56:52 Info  [Launcher] CPU: GenuineIntel Intel(R) Core(TM) i5-9600K CPU @ 3.70GHz
15:56:52 Info  [Launcher] CPU supports SSSE3: YES
15:56:52 Trace [Launcher] Loading hybris libraries
15:56:52 Trace [HybrisUtils] Loaded OS library libm.so.6
15:56:52 Trace [HybrisUtils] Loaded OS library libz.so.1
15:56:52 Trace [HybrisUtils] Loaded OS library /app/share/mcpelauncher/lib/native/x86_64/libfmod.so.12.0
load_library: Undefined symbol glMultMatrixf
load_library: Undefined symbol glFogfv
load_library: Undefined symbol glNormalPointer
load_library: Undefined symbol glVertexPointer
load_library: Undefined symbol glLightfv
load_library: Undefined symbol glLoadIdentity
load_library: Undefined symbol glRotatef
load_library: Undefined symbol glMatrixMode
load_library: Undefined symbol glPopMatrix
load_library: Undefined symbol glTranslatef
load_library: Undefined symbol glOrthof
load_library: Undefined symbol glPushMatrix
load_library: Undefined symbol glEnableClientState
load_library: Undefined symbol glShadeModel
load_library: Undefined symbol glViewport
load_library: Undefined symbol glVertexAttrib2fv
load_library: Undefined symbol glVertexAttrib1fv
load_library: Undefined symbol glValidateProgram
load_library: Undefined symbol glUniformMatrix4fv
load_library: Undefined symbol glUniform4iv
load_library: Undefined symbol glVertexAttrib1f
load_library: Undefined symbol glUniform4fv
load_library: Undefined symbol glUniform4f
load_library: Undefined symbol glUniform3i
load_library: Undefined symbol glAlphaFunc
load_library: Undefined symbol glUniform3fv
load_library: Undefined symbol glUniform2i
load_library: Undefined symbol glScalef
load_library: Undefined symbol glUniform4i
load_library: Undefined symbol glUniform2fv
load_library: Undefined symbol glUniform2f
load_library: Undefined symbol glVertexAttribPointer
load_library: Undefined symbol glUniform1iv
load_library: Undefined symbol glUniform1i
load_library: Undefined symbol glUniform1fv
load_library: Undefined symbol glUniform1f
load_library: Undefined symbol glTexParameteriv
load_library: Undefined symbol glStencilOpSeparate
load_library: Undefined symbol glStencilMaskSeparate
load_library: Undefined symbol glStencilMask
load_library: Undefined symbol glStencilFuncSeparate
load_library: Undefined symbol glFramebufferRenderbuffer
load_library: Undefined symbol glEnable
load_library: Undefined symbol glTexParameteri
load_library: Undefined symbol glBufferSubData
load_library: Undefined symbol glDrawArrays
load_library: Undefined symbol glGetRenderbufferParameteriv
load_library: Undefined symbol glDetachShader
load_library: Undefined symbol glDeleteFramebuffers
load_library: Undefined symbol glDrawElements
load_library: Undefined symbol glDeleteProgram
load_library: Undefined symbol glDepthRangef
load_library: Undefined symbol glCullFace
load_library: Undefined symbol glCreateProgram
load_library: Undefined symbol glDisableVertexAttribArray
load_library: Undefined symbol glColorPointer
load_library: Undefined symbol glDeleteRenderbuffers
load_library: Undefined symbol glPixelStorei
load_library: Undefined symbol glDeleteShader
load_library: Undefined symbol glGetProgramInfoLog
load_library: Undefined symbol glColor4f
load_library: Undefined symbol glUseProgram
load_library: Undefined symbol glClearStencil
load_library: Undefined symbol glShaderBinary
load_library: Undefined symbol glIsShader
load_library: Undefined symbol glReleaseShaderCompiler
load_library: Undefined symbol glBlendEquation
load_library: Undefined symbol glShaderSource
load_library: Undefined symbol glGetVertexAttribPointerv
load_library: Undefined symbol glDepthMask
load_library: Undefined symbol glFogf
load_library: Undefined symbol glVertexAttrib3f
load_library: Undefined symbol glUniformMatrix3fv
load_library: Undefined symbol glGetShaderInfoLog
load_library: Undefined symbol glActiveTexture
load_library: Undefined symbol glTexParameterfv
load_library: Undefined symbol glCopyTexImage2D
load_library: Undefined symbol glStencilOp
load_library: Undefined symbol glClear
load_library: Undefined symbol glIsBuffer
load_library: Undefined symbol glGetBufferParameteriv
load_library: Undefined symbol glDisable
load_library: Undefined symbol glBlendFunc
load_library: Undefined symbol glBlendEquationSeparate
load_library: Undefined symbol glFinish
load_library: Undefined symbol glUniformMatrix2fv
load_library: Undefined symbol glIsTexture
load_library: Undefined symbol glTexSubImage2D
load_library: Undefined symbol glBindFramebuffer
load_library: Undefined symbol glBlendColor
load_library: Undefined symbol glGetUniformLocation
load_library: Undefined symbol glBindBuffer
load_library: Undefined symbol glBlendFuncSeparate
load_library: Undefined symbol glBindTexture
load_library: Undefined symbol glVertexAttrib2f
load_library: Undefined symbol glBindRenderbuffer
load_library: Undefined symbol glUniform3iv
load_library: Undefined symbol glGetVertexAttribiv
load_library: Undefined symbol glDeleteTextures
load_library: Undefined symbol glFlush
load_library: Undefined symbol glClearColor
load_library: Undefined symbol glDeleteBuffers
load_library: Undefined symbol glCreateShader
load_library: Undefined symbol glDepthFunc
load_library: Undefined symbol glGetString
load_library: Undefined symbol glAttachShader
load_library: Undefined symbol glCopyTexSubImage2D
load_library: Undefined symbol glClearDepthf
load_library: Undefined symbol glVertexAttrib3fv
load_library: Undefined symbol glTexParameterf
load_library: Undefined symbol glGetAttribLocation
load_library: Undefined symbol glTexImage2D
load_library: Undefined symbol glLinkProgram
load_library: Undefined symbol glCheckFramebufferStatus
load_library: Undefined symbol glUniform2iv
load_library: Undefined symbol glColorMask
load_library: Undefined symbol glCompileShader
load_library: Undefined symbol glSampleCoverage
load_library: Undefined symbol glEnableVertexAttribArray
load_library: Undefined symbol glCompressedTexSubImage2D
load_library: Undefined symbol glUniform3f
load_library: Undefined symbol glGetTexParameteriv
load_library: Undefined symbol glFramebufferTexture2D
load_library: Undefined symbol glFrontFace
load_library: Undefined symbol glVertexAttrib4fv
load_library: Undefined symbol glGenBuffers
load_library: Undefined symbol glCompressedTexImage2D
load_library: Undefined symbol glGetFloatv
load_library: Undefined symbol glGenFramebuffers
load_library: Undefined symbol glBindAttribLocation
load_library: Undefined symbol glGenRenderbuffers
load_library: Undefined symbol glGenTextures
load_library: Undefined symbol glBufferData
load_library: Undefined symbol glHint
load_library: Undefined symbol glFogx
load_library: Undefined symbol glDisableClientState
load_library: Undefined symbol glGetActiveAttrib
load_library: Undefined symbol glIsRenderbuffer
load_library: Undefined symbol glGenerateMipmap
load_library: Undefined symbol glGetAttachedShaders
load_library: Undefined symbol glGetBooleanv
load_library: Undefined symbol glGetError
load_library: Undefined symbol glVertexAttrib4f
load_library: Undefined symbol glGetProgramiv
load_library: Undefined symbol glGetUniformfv
load_library: Undefined symbol glIsFramebuffer
load_library: Undefined symbol glTexCoordPointer
load_library: Undefined symbol glGetFramebufferAttachmentParameteriv
load_library: Undefined symbol glGetShaderiv
load_library: Undefined symbol glGetIntegerv
load_library: Undefined symbol glGetShaderPrecisionFormat
load_library: Undefined symbol glGetShaderSource
load_library: Undefined symbol glGetUniformiv
load_library: Undefined symbol glGetTexParameterfv
load_library: Undefined symbol glReadPixels
load_library: Undefined symbol glLightModelf
load_library: Undefined symbol glGetVertexAttribfv
load_library: Undefined symbol glIsEnabled
load_library: Undefined symbol glStencilFunc
load_library: Undefined symbol glIsProgram
load_library: Undefined symbol glLineWidth
load_library: Undefined symbol glScissor
load_library: Undefined symbol glGetActiveUniform
load_library: Undefined symbol glPolygonOffset
load_library: Undefined symbol glRenderbufferStorage
15:56:52 Trace [Launcher] Loading Minecraft library
15:56:52 Info  [Launcher] Loaded Minecraft library
15:56:52 Debug [Launcher] Minecraft is at offset 0x0x7f16f47c0000
15:56:52 Info  [Launcher] Game version: 0.0.0.0
15:56:52 Info  [Launcher] Applying patches
15:56:52 Info  [Launcher] Initializing JNI
15:56:52 Error [JniSupport] Missing native symbol: Java_com_mojang_minecraftpe_MainActivity_nativeRegisterThis
15:56:52 Error [JniSupport] Missing native symbol: Java_com_mojang_minecraftpe_MainActivity_nativeUnregisterThis
15:56:52 Info  [Launcher] Executing main thread
15:56:52 Trace [JniSupport] Invoking nativeRegisterThis
15:56:52 Trace [JniSupport] Invoking ANativeActivity_onCreate
15:56:52 Warn  [Main] Android stub called
15:56:52 Warn  [Main] Android stub called
15:56:52 Warn  [Main] Android stub called
15:56:52 Warn  [Main] Android stub called
15:56:52 Info  [Launcher] Loading gamepad mappings
15:56:52 Trace [Launcher] Loading gamepad mappings: /app/share/mcpelauncher/gamecontrollerdb.txt
15:56:52 Trace [Launcher] Loading gamepad mappings: /app/share/mcpelauncher/gamecontrollerdb.txt
15:56:52 Info  [Launcher] Creating window
Signal 11 received
Backtrace elements: 10
#0 /app/bin/mcpelauncher-client(_ZN12CrashHandler12handleSignalEiPv+0x12a) [0x61699a]
#1 /usr/lib/x86_64-linux-gnu/libpthread.so.0(+0x13ae0) [0x7f170461fae0]
#2 /usr/lib/x86_64-linux-gnu/libc.so.6(+0x1613b5) [0x7f17040ec3b5]
#3 /app/bin/mcpelauncher-client(_ZN15JoystickManager27handleMissingGamePadMappingENSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEES5_iiiSt8functionIFbS5_EE+0x4a2) [0x61e1d2]
#4 /app/bin/mcpelauncher-client(_ZN19GLFWJoystickManager21_glfwJoystickCallbackEii+0x215) [0x61c595]
#5 /app/bin/mcpelauncher-client(_ZN19GLFWJoystickManager9addWindowEP14GLFWGameWindow+0xc0) [0x61cfb0]
#6 /app/bin/mcpelauncher-client(_ZN14GLFWGameWindow4showEv+0xd) [0x61fdfd]
#7 /app/bin/mcpelauncher-client(_ZN10FakeLooper7prepareEv+0x4ff) [0x60158f]
#8 /app/bin/mcpelauncher-client() [0x601d9e]
#9 HYBRIS (null)+0x7f16f8edf3f2 in /home/jan/.var/app/io.mrarm.mcpelauncher/data/mcpelauncher/versions/1.16.201.01/lib/x86_64/libminecraftpe.so+0x0x471f3f2 [0x0x7f16f8edf3f2]
Dumping stack...
#3 HYBRIS (null)+0x7f16f47c0000 in /home/jan/.var/app/io.mrarm.mcpelauncher/data/mcpelauncher/versions/1.16.201.01/lib/x86_64/libminecraftpe.so+0x(nil) [0x0x7f16f47c0000]
#16 HYBRIS (null)+0x7f16f8edf3f2 in /home/jan/.var/app/io.mrarm.mcpelauncher/data/mcpelauncher/versions/1.16.201.01/lib/x86_64/libminecraftpe.so+0x0x471f3f2 [0x0x7f16f8edf3f2]
#49 HYBRIS typeinfo for JsonUtil::JsonSchemaNode_CanHaveChildren<JsonUtil::EmptyClass, RangedAttackDefinition>+0x10 in /home/jan/.var/app/io.mrarm.mcpelauncher/data/mcpelauncher/versions/1.16.201.01/lib/x86_64/libminecraftpe.so+0x0xb840000 [0x0x7f1700000000]
#62 HYBRIS typeinfo for JsonUtil::JsonSchemaNode_CanHaveChildren<JsonUtil::EmptyClass, RangedAttackDefinition>+0x12 in /home/jan/.var/app/io.mrarm.mcpelauncher/data/mcpelauncher/versions/1.16.201.01/lib/x86_64/libminecraftpe.so+0x0xb840002 [0x0x7f1700000002]
#418 HYBRIS typeinfo for JsonUtil::JsonSchemaNode_CanHaveChildren<JsonUtil::EmptyClass, RangedAttackDefinition>+0x10 in /home/jan/.var/app/io.mrarm.mcpelauncher/data/mcpelauncher/versions/1.16.201.01/lib/x86_64/libminecraftpe.so+0x0xb840000 [0x0x7f1700000000]
#464 HYBRIS typeinfo for JsonUtil::JsonSchemaNode_CanHaveChildren<JsonUtil::EmptyClass, RangedAttackDefinition>+0x12 in /home/jan/.var/app/io.mrarm.mcpelauncher/data/mcpelauncher/versions/1.16.201.01/lib/x86_64/libminecraftpe.so+0x0xb840002 [0x0x7f1700000002]
#518 HYBRIS (null)+0x7f16f8edf3f2 in /home/jan/.var/app/io.mrarm.mcpelauncher/data/mcpelauncher/versions/1.16.201.01/lib/x86_64/libminecraftpe.so+0x0x471f3f2 [0x0x7f16f8edf3f2]
#524 HYBRIS (null)+0x7f16f8edf350 in /home/jan/.var/app/io.mrarm.mcpelauncher/data/mcpelauncher/versions/1.16.201.01/lib/x86_64/libminecraftpe.so+0x0x471f350 [0x0x7f16f8edf350]
#535 HYBRIS typeinfo for JsonUtil::JsonSchemaNode_CanHaveChildren<JsonUtil::EmptyClass, RangedAttackDefinition>+0x11 in /home/jan/.var/app/io.mrarm.mcpelauncher/data/mcpelauncher/versions/1.16.201.01/lib/x86_64/libminecraftpe.so+0x0xb840001 [0x0x7f1700000001]
#543 HYBRIS typeinfo for JsonUtil::JsonSchemaNode_CanHaveChildren<JsonUtil::EmptyClass, RangedAttackDefinition>+0x10 in /home/jan/.var/app/io.mrarm.mcpelauncher/data/mcpelauncher/versions/1.16.201.01/lib/x86_64/libminecraftpe.so+0x0xb840000 [0x0x7f1700000000]
#544 HYBRIS typeinfo for ActorGoalDefinition<SlimeAttackDefinition, SlimeAttackGoal>+0x8 in /home/jan/.var/app/io.mrarm.mcpelauncher/data/mcpelauncher/versions/1.16.201.01/lib/x86_64/libminecraftpe.so+0x0xb8401e0 [0x0x7f17000001e0]
#833 HYBRIS (null)+0x7f16f8edec00 in /home/jan/.var/app/io.mrarm.mcpelauncher/data/mcpelauncher/versions/1.16.201.01/lib/x86_64/libminecraftpe.so+0x0x471ec00 [0x0x7f16f8edec00]
#834 HYBRIS (null)+0x7f16f8edecb0 in /home/jan/.var/app/io.mrarm.mcpelauncher/data/mcpelauncher/versions/1.16.201.01/lib/x86_64/libminecraftpe.so+0x0x471ecb0 [0x0x7f16f8edecb0]
#835 HYBRIS (null)+0x7f16f8eded60 in /home/jan/.var/app/io.mrarm.mcpelauncher/data/mcpelauncher/versions/1.16.201.01/lib/x86_64/libminecraftpe.so+0x0x471ed60 [0x0x7f16f8eded60]
#836 HYBRIS (null)+0x7f16f8edee40 in /home/jan/.var/app/io.mrarm.mcpelauncher/data/mcpelauncher/versions/1.16.201.01/lib/x86_64/libminecraftpe.so+0x0x471ee40 [0x0x7f16f8edee40]
#837 HYBRIS (null)+0x7f16f8edeef0 in /home/jan/.var/app/io.mrarm.mcpelauncher/data/mcpelauncher/versions/1.16.201.01/lib/x86_64/libminecraftpe.so+0x0x471eef0 [0x0x7f16f8edeef0]
#838 HYBRIS (null)+0x7f16f8edeb20 in /home/jan/.var/app/io.mrarm.mcpelauncher/data/mcpelauncher/versions/1.16.201.01/lib/x86_64/libminecraftpe.so+0x0x471eb20 [0x0x7f16f8edeb20]
#839 HYBRIS (null)+0x7f16f8edf040 in /home/jan/.var/app/io.mrarm.mcpelauncher/data/mcpelauncher/versions/1.16.201.01/lib/x86_64/libminecraftpe.so+0x0x471f040 [0x0x7f16f8edf040]
#840 HYBRIS (null)+0x7f16f8edf0a0 in /home/jan/.var/app/io.mrarm.mcpelauncher/data/mcpelauncher/versions/1.16.201.01/lib/x86_64/libminecraftpe.so+0x0x471f0a0 [0x0x7f16f8edf0a0]
#843 HYBRIS (null)+0x7f16f8edf1c0 in /home/jan/.var/app/io.mrarm.mcpelauncher/data/mcpelauncher/versions/1.16.201.01/lib/x86_64/libminecraftpe.so+0x0x471f1c0 [0x0x7f16f8edf1c0]
#844 HYBRIS (null)+0x7f16f8edf280 in /home/jan/.var/app/io.mrarm.mcpelauncher/data/mcpelauncher/versions/1.16.201.01/lib/x86_64/libminecraftpe.so+0x0x471f280 [0x0x7f16f8edf280]
#845 HYBRIS (null)+0x7f16f8edf290 in /home/jan/.var/app/io.mrarm.mcpelauncher/data/mcpelauncher/versions/1.16.201.01/lib/x86_64/libminecraftpe.so+0x0x471f290 [0x0x7f16f8edf290]
#847 HYBRIS (null)+0x7f16f8edefa0 in /home/jan/.var/app/io.mrarm.mcpelauncher/data/mcpelauncher/versions/1.16.201.01/lib/x86_64/libminecraftpe.so+0x0x471efa0 [0x0x7f16f8edefa0]
#848 HYBRIS (null)+0x7f16f8edeff0 in /home/jan/.var/app/io.mrarm.mcpelauncher/data/mcpelauncher/versions/1.16.201.01/lib/x86_64/libminecraftpe.so+0x0x471eff0 [0x0x7f16f8edeff0]

Process exited with unexpected exit code: 6
`

**Comment by ChristopherHX** [comment]
Duplicate please see here: https://github.com/ChristopherHX/mcpelauncher-manifest/issues/174#issuecomment-748459505
