### ISSUE TITLE
Unable to update

### ISSUE THREAD

**Issue by nazthelizard122** [ChristopherHX/mcpelauncher-manifest#178]
I got fedora linux installed and I went through the installation process of the launcher and it's installed but I cannot update it I got the download from https://github/ChristopherHx/Linux-packaging-scripts/releases I haven't had this issue before

**Comment by ChristopherHX** [comment]
Doesn't affect debian, ubuntu and archlinux.

Install AppImage Launcher or appimageupdate and use these tools to update the appimage. Do not install these tools as appimage they would fail too.
For appimage update see wiki draft
[appimage](https://github.com/minecraft-linux/mcpelauncher-wiki/blob/Update-wiki-for-ng/getting_started.rst#appimage)

No idk why you need to compile appimageupdate for the redhat OS or install the rpm to run proberly.

**Comment by nazthelizard122** [comment]
Is this it? https://github.com/TheAssassin/AppImageLauncher

**Comment by ChristopherHX** [comment]
Yes....
You didn't read the link I posted, before?
Otherwise you wouldn't ask, because the wiki article contains the exact the same link to https://github.com/TheAssassin/AppImageLauncher

Then right click the app in start and press update

**Comment by nazthelizard122** [comment]
I have no idea what I'm doing, an article I read says the appimagelauncher supports Ubuntu, Debian, Netrunner, and openSUSE

**Comment by ChristopherHX** [comment]
Just install the opensuse rpm, it works on my fedora vm better than the inapp updater.

Goto https://github.com/TheAssassin/AppImageLauncher/releases/tag/v2.2.0
and download the rpm for x86_64 use this one
appimagelauncher-2.2.0-travis995.0f91801.x86_64.rpm

**Comment by nazthelizard122** [comment]
Done, I ran the appimage for Minecraft and I updated it and relaunched it via the start menu and it still has an update

**Comment by nazthelizard122** [comment]
Same as before, I click update and it takes forever to update but it dosent update

**Comment by ChristopherHX** [comment]
>  I updated it and relaunched it via the start menu

You need to update it from the startmenu until the startmenu tells you there are no updates.

You may need to update multiple times.
You may find multiple appicons of the launcher with different versions, delete the older from the startmenu

**Comment by ChristopherHX** [comment]
The launcher stops showing update is available if it is uptodate, this works on fedora too.

**Comment by nazthelizard122** [comment]
When you say the startmenu, do you mean the launcher ui? (The light blue banner)

**Comment by ChristopherHX** [comment]
No
startmenu is a menu not related to this app.
If you not know what a startmenu is close this.

The launcher ui cannot update anything on opensuse, fedora, centos other rethat

**Comment by nazthelizard122** [comment]
Ok, I figured it out thanks for the help and for putting up with my nonsense
