### ISSUE TITLE
Can't start launcher on Arch Linux

### ISSUE THREAD

**Issue by jorge-aparicio** [ChristopherHX/mcpelauncher-manifest#18]
This is the terminal output for running  mcpelauncher-ui-qt in the terminal. It was working a few days ago I'm not sure if an update to arch caused this issue to emerge.

`error while loading shared libraries: libprotobuf.so.21: cannot open shared object file: No such file or directory
`

**Comment by ChristopherHX** [comment]
You need to update mcpelauncher-ui-qt (reinstall from AUR) or install my prebuild mcpelauncher-ui-qt from my linux release page via `pacman -U mcpelauncher-ui-qt*.tar.xz` or use the appimage (it includes the library and won't break on OS update of arch), known issue on updating arch

**Comment by ChristopherHX** [comment]
I deployed an update to package managment to rebuild every day, but that not means that your issue won't appear again if you choose the wrong time to do an arch update

**Comment by ChristopherHX** [comment]
Fixed now! install the protobuf package from the release page it contains the used one!
