### ISSUE TITLE
Launcher Crashed

### ISSUE THREAD

**Issue by gaarza** [ChristopherHX/mcpelauncher-manifest#193]
Did older Launcher Versions work on this PC?
```
17:43:12 Trace [HybrisUtils] Loaded OS library libz.dylib
17:43:12 Trace [HybrisUtils] Loaded OS library libm.dylib
17:43:12 Trace [HybrisUtils] Loaded OS library /private/var/folders/dl/cb8hhmgj38zcdchjrfyfttxc0000gn/T/AppTranslocation/B9D3430C-77B9-4B82-B04B-E6CB85B4B3ED/d/Minecraft Bedrock.app/Contents/Resources/mcpelauncher/lib/native/x86_64/libfmod.dylib
Signal 11 received
Backtrace elements: 7
#0 0   mcpelauncher-client                 0x0000000109f41f92 _ZN12CrashHandler12handleSignalEiPv + 226
#1 1   libsystem_platform.dylib            0x00007fff704de5fd _sigtramp + 29
#2 2   ???                                 0x0000000000000000 0x0 + 0
#3 3   mcpelauncher-client                 0x0000000109f21bcd _ZN11HookManager7LibInfoC1EPv + 29
#4 4   mcpelauncher-client                 0x0000000109f2226a _ZN11HookManager10addLibraryEPv + 90
#5 5   mcpelauncher-client                 0x0000000109c1c633 main + 7571
#6 6   libdyld.dylib                       0x00007fff702e5cc9 start + 1
Dumping stack...

Process exited with unexpected exit code: 6

```
# Disclaimer
If you don't answer these questions your issue will be closed

**Comment by ChristopherHX** [comment]
Please don't run the Launcher from an old dmg file.
- copy the app to your Application folder
- install updates
  - It will open a popup, only if it is installed to an writeable location
  - Settings>About>Check for updates will explicitly check for updates.

**Comment by ChristopherHX** [comment]
@gaarza Did you renamed the launcher from `Minecraft Bedrock Launcher.app` to `Minecraft Bedrock.app`?

**I heard of a potenially tampered Launcher from mediafire**

You find offical releases from me on github (https://github.com/ChristopherHX/osx-packaging-scripts/releases/tag/ng.dmg).
They are still unsigned, but it seems to be reasonable to increase secureity.
