### ISSUE TITLE
Launcher Crashed

### ISSUE THREAD

**Issue by saii04** [ChristopherHX/mcpelauncher-manifest#198]
Did older Launcher Versions work on this PC?
```
22:35:19 Trace [HybrisUtils] Loaded OS library libz.dylib
22:35:19 Trace [HybrisUtils] Loaded OS library libm.dylib
22:35:19 Trace [HybrisUtils] Loaded OS library /private/var/folders/s7/4tljtphs6ylglq025515v36h0000gn/T/AppTranslocation/390F1A75-4F87-4644-9F7C-2BD23476BC16/d/Minecraft Bedrock.app/Contents/Resources/mcpelauncher/lib/native/x86_64/libfmod.dylib
Signal 11 received
Backtrace elements: 7
#0 0   mcpelauncher-client                 0x00000001073d6f92 _ZN12CrashHandler12handleSignalEiPv + 226
#1 1   libsystem_platform.dylib            0x00007fff20365d7d _sigtramp + 29
#2 2   ???                                 0x0000000000000000 0x0 + 0
#3 3   mcpelauncher-client                 0x00000001073b6bcd _ZN11HookManager7LibInfoC1EPv + 29
#4 4   mcpelauncher-client                 0x00000001073b726a _ZN11HookManager10addLibraryEPv + 90
#5 5   mcpelauncher-client                 0x00000001070b1633 main + 7571
#6 6   libdyld.dylib                       0x00007fff2033c621 start + 1
Dumping stack...

Process exited with unexpected exit code: 6

```
# Disclaimer
If you don't answer these questions your issue will be closed

**Comment by ChristopherHX** [comment]
**I heard of a potenially tampered Launcher from mediafire**

You find offical releases from me on github (https://github.com/ChristopherHX/osx-packaging-scripts/releases/tag/ng.dmg).
They are still unsigned, but it seems to be reasonable to increase secureity.

Where do you get that version? It might harm your computer or credentials.

**Comment by saii04** [comment]
I found it on a youtube video, and the comments say it worked, my mac is mac os big sur 11.1 will it work? I’m just trying to play with friends?

**Comment by ChristopherHX** [comment]
I would say the version of the youtuber could have worked 3 month ago, but the youtuber (no idea who to sue, link?) seems to kill the updater of the launcher or even modify it.

The official versions works, but crashs often in settings skin editor, archivement ui.
**Allways install all updates or it will crash like that.**

Never trust any youtuber with this launcher, they are faster outdated than you can look.

**Comment by saii04** [comment]
sorry for the late reply but which one specifically can I download, as i
downloaded one of them and the application wasn't responding I have the mac
os 11.1

**Comment by saii04** [comment]
Nevermind! I got it!! Thank you for the help!
