### ISSUE TITLE
minecraft-client no longer save settings

### ISSUE THREAD

**Issue by masrourmouad** [ChristopherHX/mcpelauncher-manifest#21]
minecraft-client no longer save settings, it resets every time.
commit bae1b34

thanks

**Comment by edward3h** [comment]
Yeah I've noticed this too.

**Comment by ChristopherHX** [comment]
I can't reproduce this behavior (saves everything now for me)
Only marketplace cache loss during update, but I don't want to maintain a mirrorbranch with the old savestyle (makes building packages not easier)

**Comment by ChristopherHX** [comment]
I reverted some savepath changes in my next build (building now)

**Comment by masrourmouad** [comment]
thanks
