### ISSUE TITLE
Can't log in to Xbox Live, gray box with "Let's go" button unclickable

### ISSUE THREAD

**Issue by intagaming** [ChristopherHX/mcpelauncher-manifest#232]
I'm using 1.16.210 and the build 648 x86_64 AppImage on Arch Linux.
I clicked Sign In, type my account details, and the window closed. Then it reappears with the Xbox page to click Let's go. But it is only a grey box with the Let's go button, which can't be clicked, no avatar, no name, just a box and a button. It has the View Source menu option, I clicked and copy the url on the title bar, and paste on Firefox, and it shows my name and avatar normally, with the button clickable.
Any information on this?

**Comment by ChristopherHX** [comment]
> only a grey box with the Let's go button

We need to bundle newer qt5 in the AppImage and increase the minimum Linux version bejond ubuntu 16.04.

For the next day(s) or week(s) here a workaround
- Login just before
- You see the greyed out button, **keep the login window opened**
- Kill the launcher, **keep the login window opened**
  - you can use the Taskmanager
  - close is not enough, because it may freeze.
- close the login window, after the game is closed
- Open the game again, you will be signed in

**Comment by intagaming** [comment]
Great! The workaround is so sneaky I can't figure it out myself.
I used `xorg`, so I `xkill` and click on the client window, then run another instance of the client with `./MC.AppImage`, run the game, click Sign In, and it works! Then at this state there's a login window and the game, a little messy, but I better follow the instruction.

**Comment by ChristopherHX** [comment]
Glad you found another way..
You should better use kill not xkill, because xkill might only kill the visible window not the game.

**Comment by intagaming** [comment]
> Glad you found another way..
> 
> You should better use kill not xkill, because xkill might only kill the visible window not the game.

Yeah, the reason that I didn't go that route was that I thought killing the game would close the Login window also. There's an entry in `htop` named by the .AppImage file but I didn't try to kill that. Maybe using `kill` would work better.

**Comment by ChristopherHX** [comment]
@intagaming It seems microsoft fixed their webpage and this isn't a problem anymore. Please check it and close this if it is fixed by microsoft.

**Comment by intagaming** [comment]
> @intagaming It seems microsoft fixed their webpage and this isn't a problem anymore. Please check it and close this if it is fixed by microsoft.

It is, indeed. The page works very well! Thanks for the update.
