### ISSUE TITLE
How do enable dev mode?

### ISSUE THREAD

**Issue by nazthelizard122** [ChristopherHX/mcpelauncher-manifest#235]
In the last changelog you said I could start the ui with --enable-devmode to get it back, is there a certain file/place I have to write it?

**Comment by Haus3master** [comment]
When you are running theappimage just add the argument '--enable-devmode' example ./MC.AppImage --enable-devmode, but, the arm launcher doesn't work on devmode...

**Comment by nazthelizard122** [comment]
Thanks! Now how do I close an issue?

**Comment by Haus3master** [comment]
There should be a close button where you reply...

**Comment by nazthelizard122** [comment]
Found it!
