### ISSUE TITLE
mcpelauncher-server package missing executable

### ISSUE THREAD

**Issue by gatopeich** [ChristopherHX/mcpelauncher-manifest#24]
The [prebuilt server .deb for Ubuntu 18](https://github.com/ChristopherHX/linux-packaging-scripts/releases/download/557.ubuntu.bionic.18.04/mcpelauncher-server-e43d4eb-Linux.deb
) only has the following file: libfmod.so.9.16

Package: mcpelauncher-server:i386
Version: 20191219-211632-e43d4eb
Status: install ok installed
Priority: optional
Section: devel
Maintainer: https://github.com/minecraft-linux/mcpelauncher-manifest/issues
Installed-Size: 1632 kB
Depends: libc6 (>= 2.14), libstdc++6, libcurl4, libx11-6, zlib1g
Download-Size: unknown
APT-Manual-Installed: yes
APT-Sources: /var/lib/dpkg/status
Description: A server for Minecraft: Pocket Edition

$ dpkg -L mcpelauncher-server 
/usr
/usr/share
/usr/share/mcpelauncher
/usr/share/mcpelauncher/libs
/usr/share/mcpelauncher/libs/native
/usr/share/mcpelauncher/libs/native/libfmod.so.9.16

**Comment by ChristopherHX** [comment]
Yes I noticed it too, copied over from minecraft-linux,
but as I testing armhf now my fix will delay to be available to download page

# Important Note
the server binary can **only run 1.12.x** Minecraft server, no updates planned

**Comment by ChristopherHX** [comment]
Its was rebuild, now the latest Release includes the missing file

**Comment by gatopeich** [comment]
Still just 1.12 I guess...
