### ISSUE TITLE
Unable to login to Xbox Live

### ISSUE THREAD

**Issue by SirBenjys** [ChristopherHX/mcpelauncher-manifest#259]
I just installed the launcher and downloaded the default profile (1.16.221). I open the game, and hit "Sign In" to login to my Microsoft account, the webviewer shows me the "Let's get you signed in" page, then when I go to hit the Sign in button from there, it gives me this error: 

This site can’t be reached

The webpage at https://login.live.com/oauth20_authorize.srf?lw=1&fl=dob,easi2&xsup=1&display=android_phone&code_challenge=vAF7-sOcp_QReMmOPmaXoYjAbt7FNQSnzW5vCM-l-4Q&code_challenge_method=S256&state=UHkXxOZ_AAAAAAAAAAAAAGVtaWMgYW5kIFJlc2VhcmNoIEluc3RpdHV0aW9ucyBDZXJ0LiBBdXRob3JpdHkAAA&client_id=0000000048183522&response_type=code&scope=service%3A%3Auser.auth.xboxlive.com%3A%3AMBI_SSL&redirect_uri=ms-xal-0000000048183522%3A%2F%2Fauth might be temporarily down or it may have moved permanently to a new web address.
ERR_NAME_RESOLUTION_FAILED

I know the link should work because I pasted it in firefox, and it took me to the login site; of course, I couldn't login to the game from there. Any help?

**Comment by ChristopherHX** [comment]
Have you retried logging in once? It is possible that your network was unreachable and reconnected while you pasted it into your browser.

**Comment by ChristopherHX** [comment]
Just close the sign in window and sign in again via the game

**Comment by SirBenjys** [comment]
I have tried multiple times. It keeps doing the same thing, I don't have an amazing connection, but it should be sufficient for this, so I don't think that's the issue...

**Comment by ChristopherHX** [comment]
What OS (Operating System, Linux or macOS) are you using?
Which type of the launcher are you using?  (AppImage, flatpak, dmg)
Are you use any proxy to connect to microsoft services?

I have absolutly no idea why login.live.com isn't working for you in the login window.

Login via your installed firefox is a very complicated way, but it is possible if you compile the launcher from source and use the F12 debugger. I only provide the instruction if you really want to use the Terminal and the firefox debugger to workaround this weird failure.

**Comment by SirBenjys** [comment]
I'm using Linux (Pop OS).
I'm using flatpak, I installed it via Pop OS' App "store".
I don't think so, unless that is something that would be set up by the person in charge of internet in my house. I am not very literate when it comes to internet security measures.

I have very limited experience using the Terminal, so depending on just how complicated it would be, I might be willing to try that.

**Comment by ChristopherHX** [comment]
So you could also try the AppImage, if the flatpak sandbox breaks it https://github.com/ChristopherHX/linux-packaging-scripts/releases/latest

This way of sign in is really painful and a lot of work
```
sudo apt-get install git cmake make clang libssl-dev libpng-dev libx11-dev libxi-dev libcurl4-openssl-dev libudev-dev libevdev-dev libegl1-mesa-dev libasound2
git clone https://github.com/minecraft-linux/mcpelauncher-manifest.git --recursive -b ng
cd mcpelauncher-manifest
CC=clang CXX=clang++ cmake . -DJNI_USE_JNIVM=On -DCMAKE_BUILD_TYPE=Debug -DJNIVM_ENABLE_TRACE=On -DBUILD_WEBVIEW=OFF -DXAL_WEBVIEW_USE_CLI=ON -DXAL_WEBVIEW_USE_QT=OFF -DENABLE_QT_ERROR_UI=OFF
make
```
Then start the game via the cli, if the flatpak was used this command should work with game 1.16.221.01
```
./mcpelauncher-client/mcpelauncher-client -dg ~/.var/app/io.mrarm.mcpelauncher/data/mcpelauncher/versions/1.16.221.01
```
- If you press sign in you will find a link in the terminal, open it in firefox
- open the debugger of firefox with f12
- try to sign in
- copy the last url it tries to open (I used the chromium debugger-> Network, the url to copy starts with `xal`)
- paste that url into the terminal press enter, the game should continue
- press ctrl-c in the terminal after it ask's you to open another url (also in the terminal)
- you should now be signed in, hopefully also in the flatpak

I haven't used manual login since a half year, and this instruction may contains any kind of errors.
You can delete `~/mcpelauncher-manifest` after this, without loosing data

_original instruction which was even harder to use https://github.com/minecraft-linux/mcpelauncher-manifest/issues/374#issuecomment-674563699_

**Comment by SirBenjys** [comment]
I got to pressing sign in and now I don't see a link in the terminal. On the game screen it is loading and it says "connecting".

**Comment by ChristopherHX** [comment]
Was anything else in the Terminal? like an error (I guess you are in a different time zone)

Otherwise this might indicate another internet connection problem with microsoft servers on your end.

**Comment by SirBenjys** [comment]
There is something else going on in the terminal, it shows a set of different messages like this that repeat rapidly, it shows the time and the same messages over and over.

`12:32:49 Debug [JNIVM] InternalFindClass com/mojang/minecraftpe/MainActivity
12:32:49 Debug [JNIVM] Invoked Unknown Member Function Class=`com/mojang/minecraftpe/MainActivity` Method=`tick` Signature=`()V`
12:32:49 Debug [JNIVM] InternalFindClass com/mojang/minecraftpe/MainActivity
12:32:49 Debug [JNIVM] Call Member Function Class=`com/mojang/minecraftpe/MainActivity` Method=`getCursorPosition` Signature=`()I``

**Comment by ChristopherHX** [comment]
Only sending 3 lines of a 1000+ lines log is as helpful as:
```
```

I guess I have enabled to much logging for you
open a new terminal and recompile, this should be very silent now
```
cd mcpelauncher-manifest
CC=clang CXX=clang++ cmake . -DJNI_USE_JNIVM=On -DCMAKE_BUILD_TYPE=Release -DJNIVM_ENABLE_TRACE=OFF -DBUILD_WEBVIEW=OFF -DXAL_WEBVIEW_USE_CLI=ON -DXAL_WEBVIEW_USE_QT=OFF -DENABLE_QT_ERROR_UI=OFF
make
```

Then run again, with less terminal spam
```
./mcpelauncher-client/mcpelauncher-client -dg ~/.var/app/io.mrarm.mcpelauncher/data/mcpelauncher/versions/1.16.221.01
```

**Comment by SirBenjys** [comment]
I have concluded that the issue has something to do with my wifi, because I tried installing the game on my phone, and it gave me the same error, but after turning my wifi off and using data instead, they allowed me to login. I have no idea why it doesn't work, (it has in the past). Thanks for your efforts though.
