### ISSUE TITLE
Crash with Error Code 2 in 1.14.2.50

### ISSUE THREAD

**Issue by Xico26** [ChristopherHX/mcpelauncher-manifest#27]
Hi. 
I installed this version because i wasn't able to play the "original" one.
I'm trying to play 1.14.2.50 but I get this error:

/usr/bin/mcpelauncher-client: 2: /usr/bin/mcpelauncher-client: Syntax error: end of file unexpected (expecting ")")
Process exited with unexpected exit code: 2

Can you help me?
Thanks :smile:

**Comment by ChristopherHX** [comment]
Syntax Error, How do you start it?
Something is not correct, but I don't know what.
bash give you that error if don't close the opened bracket "("
Same issue as this one https://github.com/minecraft-linux/mcpelauncher-manifest/issues/207

Proposed solution uninstall the launcher and install it again (Or try the appimage)

**Comment by Xico26** [comment]
I've already tried that and also in a VM. I don't know what to do. How can I edit the file and put the correct thing?

**Comment by ChristopherHX** [comment]
If you installed the launcher .deb's, please try starting it from terminal
`mcpelauncher-client -dg ~/.local/share/mcpelauncher/versions/1.14.2.50`

**Comment by ChristopherHX** [comment]
Please add the faulting build name from download page (because it could be a bug specfic to only some builds)

**Comment by Xico26** [comment]
I installed this:
mcpelauncher-client-d2fd533-Linux.deb

**Comment by Xico26** [comment]
> If you installed the launcher .deb's, please try starting it from terminal
> `mcpelauncher-client -dg ~/.local/share/mcpelauncher/versions/1.14.2.50`

It doesn't work :cry:

**Comment by Xico26** [comment]
franciscomaia@franciscomaia-Aspire-A515-51G:~$  mcpelauncher-client -dg ~/.local/share/mcpelauncher/versions/1.14.2.50
bash: /usr/bin/mcpelauncher-client: impossível executar o arquivo binário: Erro de formato de executável

**Comment by Xico26** [comment]
> franciscomaia@franciscomaia-Aspire-A515-51G:~$ mcpelauncher-client -dg ~/.local/share/mcpelauncher/versions/1.14.2.50
> bash: /usr/bin/mcpelauncher-client: impossível executar o arquivo binário: Erro de formato de executável

Impossible to execute the binary archive. Error of executable format (Sorry for bad Translation)

**Comment by ChristopherHX** [comment]
You hopefully did not tried installing and launching the armhf Release on x86,
What OS?
`mcpelauncher-client-d2fd533-Linux.deb` exists in armhf and x86

**Comment by Xico26** [comment]
I installed armhf and I'm using Mint 19.3

**Comment by ChristopherHX** [comment]
Install the right one **only install armhf on ARM DEVICES, like Raspberry Pi and Nintento switch**
The right one for you is `ubuntu.bionic.18.04`
https://github.com/ChristopherHX/linux-packaging-scripts/releases/tag/674.ubuntu.bionic.18.04

**Comment by Xico26** [comment]
Do I need to remove the ARMHF?

**Comment by Xico26** [comment]
Worked!!!! That was my fault...

**Comment by Xico26** [comment]
But how do I put in Full Screen?

**Comment by ChristopherHX** [comment]
Press F11

**Comment by Xico26** [comment]
Thanks ;-;
