### ISSUE TITLE
when you try to open achievments the game crashes

### ISSUE THREAD

**Issue by Benrocks120** [ChristopherHX/mcpelauncher-manifest#270]
can pls fix this because i  like to see my achievments in the game

**Comment by Haus3master** [comment]
This is a known bug and is low-priority for the Dev

**Comment by GameParrot** [comment]
This no longer happens in Minecraft version 1.17.30.

**Comment by ChristopherHX** [comment]
It no longer open in 1.17.40 Mojang does a good job :/, well it does nothing.
