### ISSUE TITLE
Marketplace will not open no matter what

### ISSUE THREAD

**Issue by werty23111** [ChristopherHX/mcpelauncher-manifest#273]
I need the market place to download the music files

**Comment by Haus3master** [comment]
> I need the market place to download the music files

Install 1.16.201 version, marketplace works in that version, download music files from there and play the new versions after doing so, the music will play

**Comment by werty23111** [comment]
ohhhhhh ok thank you so much

**Comment by Haus3master** [comment]
Your welcome!
