### ISSUE TITLE
Licence error

### ISSUE THREAD

**Issue by TheSpyGorillas** [ChristopherHX/mcpelauncher-manifest#277]
I used my google account, downloaded latest version, but when it opens it gives me licence error that it cant recognize device. what should i do?
![Screen Shot 2021-06-18 at 7 04 34 PM](https://user-images.githubusercontent.com/62268883/122588796-30de8e00-d068-11eb-858d-26d23c6e40f4.png)

**Comment by Haus3master** [comment]
Your Google account must have Minecraft already purchased on it, of you use a generic Google account and then an apk file, it won't work...

**Comment by TheSpyGorillas** [comment]
yes i do have it purchased. but it actually just fixed itseld. thanks for the response.
