### ISSUE TITLE
Launcher not found in PATH variable

### ISSUE THREAD

**Issue by Creeperface01** [ChristopherHX/mcpelauncher-manifest#28]
Everytime I start the game I get this error. Even though I tried to removing the app and installing again from the dmg file.

![image](https://user-images.githubusercontent.com/10363500/71542979-ec3fce00-296d-11ea-83fc-2af9ac63b9b8.png)

**Comment by ChristopherHX** [comment]
No MacOs Catalina support, same as the original
Yeay I missed adding min and max supported MacOs versions in recent releases.

**Comment by Creeperface01** [comment]
Ah thanks and what's the problem?

**Comment by ChristopherHX** [comment]
Removed 32bit app support (Minecraft is still only 32bit on the playstore)
I'm not trying to hack 32bit support back Macos 10.15

**Comment by Mhowser** [comment]
Is it possible to make a custom crash message that tells the user that Catalina is supported?

**Comment by ChristopherHX** [comment]
Yes, thats possible with some UI changes.
Additionally all other Error Messages needs to get more understandable Info texts with links to possible Solutions. And Improve Error Handling also in minecraft-linux, e. g. a Messagebox which states "unsupported Version" instead of a crash (that nearly nobody reads or understand)

**Comment by Mhowser** [comment]
That would definitely help users who are new to this project.

**Comment by ChristopherHX** [comment]
Now marked as unsupported at the download page and ReadMe, might be working if either mojang (provides Minecraft android as x86_64) or mrarm (minecraft-linux will hack 32bit back to Catalina)

**Comment by kode54** [comment]
This information from the CrossOver developers in [this email post](https://www.winehq.org/pipermail/wine-devel/2019-December/156602.html) may help with development of a 64 bit version of the launcher, by using the same complex 32 on 64 but system they use. Of course, they don’t document their internal trick to using it, so it will require disabling SIP.

**Comment by ChristopherHX** [comment]
At least the compiler seems to work on linux64, after compiling it (linking clang took 14GB+ of my RAM, never saw such heavy usage).
It generates all assembler to call 32 bit code and the reverse,
but it outputs insane errors, special for c++ gnus stdc++libs.

**Comment by ChristopherHX** [comment]
The compiler on its own won't do the Job, it might be easier to fix my win32 port and let that run via crossover wine (built from source), if that would work.

**Comment by ChristopherHX** [comment]
**WIP** Catalina support will begin with Minecraft 1.16 (beta) x64.
The launcher will get 64bit support.
You won't be able to start < 1.16

**Comment by ChristopherHX** [comment]
Please Test https://github.com/ChristopherHX/osx-packaging-scripts/releases/download/ng.dmg/Minecraft_Bedrock_Launcher.0.0.52.dmg on macOS 10.12+
Logout and login again to google, to be able to download 64bit versions.
It should now be able to install updates without open the Webbrowser,
delta updates should work soon (avoids downloading the full dmg every time).
**(DO NOT press skip update or autoupdate)**
On 10.15+ Do not start versions with (32bit) in its name or you get the old error.
**This is still experimental and may crash after playing some time**

**Comment by cyphr3x** [comment]
This is working pretty well and I can now access my PMMP servers on mac.  @ChristopherHX you are amazing.  Thank you for your work!

**Comment by ChristopherHX** [comment]
Credits to mrarm (minecraft-linux) for fixing and porting my 64bit demo to be playable.

**Comment by ChristopherHX** [comment]
I close this, because I removed that message.
Catalina users get a notification that they cannot use the launcher if it's my fork.
If they ignore that they get a report that this launcher cannot run any minecraft version on that OS.

If they use ngpreview they get a warning if they still have a x86 (32bit login) but running 10.15+. (logout and login to get rid of it)

The UI have still a lot if open bugs, it's easy to find them.
