### ISSUE TITLE
Cannot use the launcher because of the reason..

### ISSUE THREAD

**Issue by UnknownBinary009** [ChristopherHX/mcpelauncher-manifest#292]
The reason is so, when i firstly installed the launcher everything were fine except of one thing the Login option it just supports google but i bought Minecraft Bedrock Edition on AppStore (IOS) so i cannot use the launcher i dont know why it doesnt support appstore's login options.. Please try to make an update for Apple support

**Comment by chinoto** [comment]
It isn't mentioned in the README unfortunately, but this project is specifically for getting the Android version of Minecraft to run on other platforms.

**Comment by UnknownBinary009** [comment]
I mean apple account support if its bought on apple account then it should install the APK

**Comment by ChristopherHX** [comment]
> if its bought on apple account then it should install the APK

I cannot do that, doing this is the same thing as pirating the game in my country.

> Each version of Minecraft is sold separately and not interchangeable

[Source](https://help.minecraft.net/hc/en-us/articles/360042699152-Can-I-Swap-my-Version-of-Minecraft-)
