### ISSUE TITLE
Crafting is bugged

### ISSUE THREAD

**Issue by UnknownBinary009** [ChristopherHX/mcpelauncher-manifest#294]
I CANNOT CRAFT IT DOESNT WORK IF I CRAFT A FRICKIN CRAFTING TABLE IT COMES OUT A WOODEN BUTTON WHAT IS THIS?????? IS THIS EVEN BEDROCK EDITION FOR LINUX/MAC I DONT THINK SO.... FIX IT

**Comment by ChristopherHX** [comment]
THEN DON'T USE THIS LAUNCHER.
MOJANG'S FAULT ON INTEL ANDROID.
