### ISSUE TITLE
I need help importing mods to Minecraft

### ISSUE THREAD

**Issue by CyberBacon07** [ChristopherHX/mcpelauncher-manifest#295]
I've been digging around for a while now and I still can't find how to import mods to the game.

**Comment by Is-it-all-a-dream** [comment]
I'm not sure if it is the most efficient way, but I convert the .mcaddon file to a .zip file, then extract the folder from the .mcaddon file and then drag the folder into the behaviour pack folder. I think if it were an official Minecraft launcher, double-clicking a .mcaddon file would automatically import it, but it doesn't work like that for me. Hope this helps!

**Comment by CyberBacon07** [comment]
it worked thanks!
