### ISSUE TITLE
Cant set Alt as my sprint key

### ISSUE THREAD

**Issue by technicaldiff** [ChristopherHX/mcpelauncher-manifest#297]
So i tried to change my sprint key to alt and it doesnt work
Switching to other keys do work tho

**Comment by ChristopherHX** [comment]
Please test again in 0.3.0-rc1.
https://github.com/ChristopherHX/linux-packaging-scripts/releases/tag/v0.3.0-rc1-673

I addressed your issue.

**Comment by technicaldiff** [comment]
Alt key works!.It registers as button 18 and works
