### ISSUE TITLE
3 issues

### ISSUE THREAD

**Issue by JustTalDevelops** [ChristopherHX/mcpelauncher-manifest#3]
1. View automatically scales to mobile
2. Max render distance is 9 chunks
3. Some buttons such as CTRL do not work

**Comment by ChristopherHX** [comment]
4. Button 9, shift,  up, left, right, down currently not working too

**Comment by ChristopherHX** [comment]
Points 3 and 4 are solved now

**Comment by ChristopherHX** [comment]
@JustTalDevelops Point 2
I don't know but in 1.14.0.6, I can now set renderdistance from 6 up to 20 chunks
Point 1 could be done with more Patches from the origin
