### ISSUE TITLE
1.17.40 crashes on startup.

### ISSUE THREAD

**Issue by GameParrot** [ChristopherHX/mcpelauncher-manifest#317]
Version 1.17.40.06 crashes immediately after starting. The Launcher says, "Your previously downloaded Minecraft Version might be unsupported or just corrupted.
if you wanted to play a Beta or a new Release please wait patiently for an update,
please choose a compatible version from the profile Editor
otherwise if you have updated the Launcher recently.
e.g. a crash please delete it in Settings,
then download it again via the updated Launcher."

**Comment by ChristopherHX** [comment]
No crash works as indeed.
This message is shown if you enable **unsupported settings**, which are hidden or you have an very old version.

- download the launcher from flatpak **beta**, enshure you are on **0.3.0-rc2**.
- Open the discord channel
- select `#development`
- download the two files hidden behind a spoiler (x86_64)
- put them into the mods folder
- If you own the game + connected to internet you get rid of the message
