### ISSUE TITLE
Big buffering throughout switching servers or joining them

### ISSUE THREAD

**Issue by Bhaggo** [ChristopherHX/mcpelauncher-manifest#34]
Is it just me or when using 1.13 and higher on Christopher's fork, transferring to a game mode in a server, takes ridicoulously long, for example, it takes ages to render and load cubecraft compared to other consoles and for example, if I am in the hive server running 1.13 and I click a gamemode, it takes centuries to load, is that just an issue that will never be fixed?

Mac os high sierra

**Comment by ChristopherHX** [comment]
Switch to better supported linux to get a **huge** performance gain, and use the GPU directly (macOS use a slower glitch workaround with google/angle)
