### ISSUE TITLE
xbox login does not work with appimage

### ISSUE THREAD

**Issue by SirRujak** [ChristopherHX/mcpelauncher-manifest#35]
When attempting to log in to xbox live with the appimage build the login fails due to the msa-daemon never being called. What I believe to be the pertinent parts of the log are posted below. If the rest is needed I'll be happy to supply it.

```
13:23:39 Info  [Minecraft] NO LOG FILE! - IPv4 supported, port: 51127
13:23:39 Info  [Minecraft] NO LOG FILE! - IPv6 supported, port: 53381
13:23:39 Debug [XSAPI.Android] sign_in_impl: will NOT be showing UI
13:23:39 Info  [com::microsoft::xbox::idp::interop::Interop::LogTelemetrySignIn] API - signin_silently - :Entering
13:23:39 Info  [DaemonLauncher] Daemon file exists, but we could not open it (Failed to connect); starting the service anyways
13:23:39 Trace [DaemonLauncher] Starting daemon: 
13:23:39 Error [DaemonLauncher] execv error -1
```

There is a workaround for the issue found in an issue [on the main repo](https://github.com/minecraft-linux/mcpelauncher-manifest/issues/152). While the workaround works it isn't something that I can get less technical users to use most of the time. Any assistance is greatly appreciated!

**Comment by ChristopherHX** [comment]
Should work now, fixed with the google sign in issue with one line in the buildscript

**Comment by ChristopherHX** [comment]
All issues with xbl startup fail are now issues from minecraft-linux/msa-manifest, until it is more reliable. Now it will crash if the msa-daemon fails to handle it before the stackoverflow aborts
