### ISSUE TITLE
Crash in two player realm on 1.14.20.1

### ISSUE THREAD

**Issue by kode54** [ChristopherHX/mcpelauncher-manifest#37]
Here is the log:

I can't really recall what was going on that exactly triggered the crash. Running the MCPELauncher packages you just posted a few days ago:

```
local/mcpelauncher-linux-git MacOsLatest.r9.g132cbf3-1
    Minecraft: Pocket Edition launcher for Linux (Fork)
local/mcpelauncher-msa-git v0.1.beta.2.r6.g029fde6-1
    Microsoft Account authentication daemon for mcpelauncher
local/mcpelauncher-msa-ui-qt-git v0.1.beta.2.r6.g029fde6-1
    Microsoft Account authentication user interface (Qt) for the
    mcpelauncher-msa-daemon
local/mcpelauncher-ui-git v0.1.beta.1.r17.g27833c2-1
    Minecraft: PE Linux launcher UI
```

[mcpelauncher.log.txt](https://github.com/ChristopherHX/mcpelauncher-manifest/files/4145825/mcpelauncher.log.txt)

**Comment by ChristopherHX** [comment]
You possible ran out of 32bit memory, this alpha launcher has known memory leaks with pseudo java jni

**Comment by ChristopherHX** [comment]
Crash reason not worth the effort
