### ISSUE TITLE
crash with prime-run

### ISSUE THREAD

**Issue by KingTheGuy** [ChristopherHX/mcpelauncher-manifest#38]
crashes when i try to run the gaming using my dedicated gpu. nvidia. prime-run.

15:55:36 Info [Launcher] Version: client 10b2d53 / manifest 132cbf3
15:55:36 Info [Launcher] CPU: GenuineIntel Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
15:55:36 Info [Launcher] CPU supports SSSE3: YES
15:55:36 Trace [Launcher] Loading hybris libraries
15:55:36 Trace [HybrisUtils] Loaded OS library /usr/share//mcpelauncher/libs/native/libfmod.so.9.16
15:55:36 Trace [HybrisUtils] Loaded OS library libm.so.6
15:55:36 Trace [HybrisUtils] Loaded OS library libz.so.1
15:55:36 Info [Launcher] Creating window
15:55:36 Trace [Launcher] Loading gamepad mappings: /usr/share//mcpelauncher/gamecontrollerdb.txt
15:55:36 Trace [Launcher] Loading gamepad mappings: /usr/share/mcpelauncher/gamecontrollerdb.txt
EGLUT: failed to create surface
Process exited with unexpected exit code: 1

**Comment by ChristopherHX** [comment]
Missing 32 bit mesa drivers or incompatible GPU with unsupported prime-run / bumblebee,
only nvidia-prime is known to work flawless with optimus

**Comment by KingTheGuy** [comment]
as far as i can tell, i do have the 32bit mesa drivers, also using nvidia-prime.

**Comment by ChristopherHX** [comment]
nvidia prime != prime-run/bumblebee
You need to reinstall it correctly, nvidia prime doesn't allow gpu switching while running the desktop (you need to login / logout with it)
Your error has nothing to do with this launcher at all

**Comment by kanafutile** [comment]
@KingTheGuy I found a workaround/fix. 

[Here it is.](https://gist.github.com/kanafutile/d77b5b89ff2c2aa32c77fa57e12bfc1f)

This is how to apply it:
In Arch Linux case, you must apply the patch after cloning `mcpelauncher-linux-git.git` and `cd`ing into `mcpelauncher-linux-git/src/mcpelauncher-manifest`.
In Debian & Solus cases, you must apply the patch after cloning `mcpelauncher-manifest.git` and `cd`ing into `mcpelauncher-manifest` (or `mcpelauncher` if you strictly follow instructions from README).
```sh
wget https://gist.githubusercontent.com/kanafutile/d77b5b89ff2c2aa32c77fa57e12bfc1f/raw/e7a2e06ee7eb56ca9b5649a880e509051f63ea10/eglut_from_mesa_demos.patch
patch eglut/src/eglut.c eglut_from_mesa_demos.patch
```
