### ISSUE TITLE
mcpelauncher-ui-git for Arch is missing libuv dependency

### ISSUE THREAD

**Issue by kode54** [ChristopherHX/mcpelauncher-manifest#39]
I totally missed this one. I only noticed it on a new virtual machine which I just set up a few days ago, where libuv didn't end up installed as a dependency of something else.

**Comment by ChristopherHX** [comment]
zenity is also a missing optional dependency but how to add it as optional (I'm new to archlinux)

**Comment by ChristopherHX** [comment]
the same applies to all .deb's

**Comment by kode54** [comment]
I'm not sure it should be an optdepend, since it's required to actually launch the current binaries. The Qt launcher will not open without it.
