### ISSUE TITLE
Minecraft crashes immediately with exit code 1

### ISSUE THREAD

**Issue by i-use-arch-btw** [ChristopherHX/mcpelauncher-manifest#51]
Error: `EGLUT: failed to initialize EGL display`

Doesn't work even with the 32 bit drivers installed. Used to work before, borked after system upgrade.

OS: Arch Linux
GPU: NVIDIA Geforce GTX 1050 Ti
Driver version: 440.64-1

**Comment by ChristopherHX** [comment]
`Doesn't work even with the 32 bit drivers installed. Used to work before, borked after system upgrade.`
Please learn how GNU/Linux work.
Archlinux is only for andvanced users, please reinstall the 32bit mesa (egl drivers)
You uninstalled it blindly during upgrade

**Comment by ChristopherHX** [comment]
Why this issue every time?
Closed a lot of times and it comes again.
Does the documentation lacks the dependeny?
