### ISSUE TITLE
mcpelauncher woks on Debian Jessie but unstable exept beta 1.16

### ISSUE THREAD

**Issue by masrourmouad** [ChristopherHX/mcpelauncher-manifest#53]
I know that Jessie is quite old, but when saw you support Ubuntu 16.04 32 bit, my heart was filled with hope, please if its possible to build an Appimage for Debian Jessie.
Thanks.

**Comment by ChristopherHX** [comment]
Doesn't the appimage run on debian jessie?
The only problem is qt5, as qt5.9 is required without porting the code back to older qt5.
The 32bit appimage was a little hack of the original buildscript for the appimage (it pulled a ppa for qt5.9, which supported 32bit too)

**Comment by masrourmouad** [comment]
i need just mcpelauncher-client for single player no launcher needed.
thanks.

**Comment by ChristopherHX** [comment]
I guess just build this repo https://github.com/ChristopherHX/mcpelauncher-manifest#debian
All dependencies for the mcpelauncher-client should be installable

**Comment by masrourmouad** [comment]
wont compile

**Comment by masrourmouad** [comment]
![test](https://user-images.githubusercontent.com/403487/77861736-c34e0400-720e-11ea-8e87-be81af3a7ea7.png)

it crashes any idea
Signal 11 received
Backtrace elements: 22
#0 ./mcpelauncher-client(_ZN12CrashHandler12handleSignalEiPv+0xf1) [0x82bf661]
#1 linux-gate.so.1(__kernel_sigreturn+0) [0xb77a8d1c]
#2 /usr/lib/i386-linux-gnu/dri/i965_dri.so(+0x207f9a) [0xb3979f9a]
#3 /usr/lib/i386-linux-gnu/dri/i965_dri.so(+0x207bdd) [0xb3979bdd]
#4 /usr/lib/i386-linux-gnu/dri/i965_dri.so(+0x207d70) [0xb3979d70]
#5 /usr/lib/i386-linux-gnu/dri/i965_dri.so(+0x222463) [0xb3994463]
#6 /usr/lib/i386-linux-gnu/dri/i965_dri.so(+0x27a071) [0xb39ec071]
#7 /usr/lib/i386-linux-gnu/dri/i965_dri.so(+0x28b6ca) [0xb39fd6ca]
#8 /usr/lib/i386-linux-gnu/dri/i965_dri.so(+0x28b792) [0xb39fd792]
#9 /usr/lib/i386-linux-gnu/dri/i965_dri.so(+0x2873a4) [0xb39f93a4]
#10 /usr/lib/i386-linux-gnu/dri/i965_dri.so(+0x286d9c) [0xb39f8d9c]
#11 /usr/lib/i386-linux-gnu/dri/i965_dri.so(+0x286ef6) [0xb39f8ef6]
#12 /usr/lib/i386-linux-gnu/dri/i965_dri.so(+0x286d9c) [0xb39f8d9c]
#13 /usr/lib/i386-linux-gnu/dri/i965_dri.so(+0x286f5f) [0xb39f8f5f]
#14 /usr/lib/i386-linux-gnu/dri/i965_dri.so(+0x286d9c) [0xb39f8d9c]
#15 /usr/lib/i386-linux-gnu/dri/i965_dri.so(+0x286bce) [0xb39f8bce]
#16 /usr/lib/i386-linux-gnu/dri/i965_dri.so(+0x28bcea) [0xb39fdcea]
#17 /usr/lib/i386-linux-gnu/dri/i965_dri.so(+0x2941e7) [0xb3a061e7]
#18 /usr/lib/i386-linux-gnu/dri/i965_dri.so(+0x20f14d) [0xb398114d]
#19 /usr/lib/i386-linux-gnu/dri/i965_dri.so(+0x107c08) [0xb3879c08]
#20 HYBRIS (null)+-1345351893 in libminecraftpe.so+0x3b6af2b [0xafcf8f2b]
#21 [(nil)]
Dumping stack...
#423 HYBRIS (null)+-1287476672 in libminecraftpe.so+0x729ca40 [0xb342aa40]
#424 HYBRIS (null)+0 in libminecraftpe.so+0x7376594 [0xb3504594]
#431 HYBRIS AppPlatform_android23::readAssetFile(Core::Path const&)+0 in libminecraftpe.so+0x95a2a0 [0xacae82a0]
#675 HYBRIS (null)+-1287476672 in libminecraftpe.so+0x729ca40 [0xb342aa40]
#678 HYBRIS (null)+-1345351893 in libminecraftpe.so+0x3b6af2b [0xafcf8f2b]
#682 HYBRIS (null)+-1345351921 in libminecraftpe.so+0x3b6af0f [0xafcf8f0f]
#692 HYBRIS (null)+-1287476672 in libminecraftpe.so+0x729ca40 [0xb342aa40]
#730 HYBRIS (null)+-1287476672 in libminecraftpe.so+0x729ca40 [0xb342aa40]
#731 HYBRIS (null)+0 in libminecraftpe.so+0x7376028 [0xb3504028]
#733 HYBRIS (null)+-1317618766 in libminecraftpe.so+0x55ddbb2 [0xb176bbb2]
#734 HYBRIS (null)+-1345354319 in libminecraftpe.so+0x3b6a5b1 [0xafcf85b1]
#740 HYBRIS (null)+-1287476672 in libminecraftpe.so+0x729ca40 [0xb342aa40]
#742 HYBRIS (null)+-1345353192 in libminecraftpe.so+0x3b6aa18 [0xafcf8a18]
#746 HYBRIS (null)+-1345353295 in libminecraftpe.so+0x3b6a9b1 [0xafcf89b1]
#748 HYBRIS (null)+-1286587656 in libminecraftpe.so+0x7375af8 [0xb3503af8]
#753 HYBRIS (null)+-1286587644 in libminecraftpe.so+0x7375b04 [0xb3503b04]
#756 HYBRIS (null)+-1286587656 in libminecraftpe.so+0x7375af8 [0xb3503af8]
#758 HYBRIS operator delete(void*)+28 in libminecraftpe.so+0x54b1e8c [0xb163fe8c]
#763 HYBRIS (null)+-1286587644 in libminecraftpe.so+0x7375b04 [0xb3503b04]
#766 HYBRIS (null)+-1395007231 in libminecraftpe.so+0xc10101 [0xacd9e101]
#776 HYBRIS (null)+-1287476672 in libminecraftpe.so+0x729ca40 [0xb342aa40]
#778 HYBRIS (null)+-1345341752 in libminecraftpe.so+0x3b6d6c8 [0xafcfb6c8]
#790 HYBRIS (null)+-1287476672 in libminecraftpe.so+0x729ca40 [0xb342aa40]
#801 HYBRIS (null)+-1286587644 in libminecraftpe.so+0x7375b04 [0xb3503b04]
#802 HYBRIS (null)+-1318220056 in libminecraftpe.so+0x554aee8 [0xb16d8ee8]
#803 HYBRIS (null)+-1317617933 in libminecraftpe.so+0x55ddef3 [0xb176bef3]
#805 HYBRIS (null)+-1318339352 in libminecraftpe.so+0x552dce8 [0xb16bbce8]
#848 HYBRIS (null)+-1287520256 in libminecraftpe.so+0x7292000 [0xb3420000]
#855 HYBRIS (null)+-1287476735 in libminecraftpe.so+0x729ca01 [0xb342aa01]
#879 HYBRIS (null)+-1358430209 in libminecraftpe.so+0x2ef1fff [0xaf07ffff]
#882 HYBRIS (null)+-1358430209 in libminecraftpe.so+0x2ef1fff [0xaf07ffff]
#898 HYBRIS operator delete(void*)+28 in libminecraftpe.so+0x54b1e8c [0xb163fe8c]
#904 HYBRIS (null)+-1287476734 in libminecraftpe.so+0x729ca02 [0xb342aa02]
#922 HYBRIS Core::Result::~Result()+9 in libminecraftpe.so+0x3cbbd19 [0xafe49d19]
#925 HYBRIS (null)+-1287476672 in libminecraftpe.so+0x729ca40 [0xb342aa40]
#964 HYBRIS operator delete(void*)+6 in libminecraftpe.so+0x54b1e76 [0xb163fe76]
#965 HYBRIS (null)+-1287476672 in libminecraftpe.so+0x729ca40 [0xb342aa40]
#966 HYBRIS (null)+-1318481556 in libminecraftpe.so+0x550b16c [0xb169916c]
#968 HYBRIS (null)+-1287476672 in libminecraftpe.so+0x729ca40 [0xb342aa40]
#970 HYBRIS (null)+-1287476672 in libminecraftpe.so+0x729ca40 [0xb342aa40]
#974 HYBRIS operator delete(void*)+28 in libminecraftpe.so+0x54b1e8c [0xb163fe8c]
#981 HYBRIS (null)+-1287476672 in libminecraftpe.so+0x729ca40 [0xb342aa40]
#996 HYBRIS (null)+-1287476672 in libminecraftpe.so+0x729ca40 [0xb342aa40]
#998 HYBRIS (null)+-1397853282 in libminecraftpe.so+0x95939e [0xacae739e]

**Comment by masrourmouad** [comment]
![works](https://user-images.githubusercontent.com/403487/77862135-6a339f80-7211-11ea-9c1c-1f394b7bd91e.png)

**Comment by masrourmouad** [comment]
works
mcpe 1.13.1.5
debian jessie
32 bit

using mcpelancher-client
and gcc 5.2-dev libstdc++6

**Comment by ChristopherHX** [comment]
Like I said in my Versions README of the launcher, it is very unstable.
Your posted crash is inside your intel drivers (might update them mesa3d.org, build from source).
Debian jessie has version 10 preinstalled, but version 20 is out.
Eventually it would be good to add some errorhandling around the Minecraft PE Game.

**Comment by masrourmouad** [comment]
only mcpelancher-client v Dec 22 2019 works, the now ones wont.
Btw thanks for the respond.

**Comment by masrourmouad** [comment]
tested 1.14.30.2 also works

**Comment by masrourmouad** [comment]
when works log:
Aborted
17:37:19 Info  [Launcher] Version: client 7c17ac3 / manifest 45f9d98
17:37:19 Info  [Launcher] CPU: GenuineIntel Intel(R) Core(TM) i5-4570 CPU @ 3.20GHz
17:37:19 Info  [Launcher] CPU supports SSSE3: YES
17:37:19 Trace [Launcher] Loading hybris libraries
17:37:19 Trace [HybrisUtils] Loaded OS library /home/momo/games/mcpe-1.13.1.5/libs/native/libfmod.so.9.16
17:37:19 Trace [HybrisUtils] Loaded OS library libm.so.6
17:37:19 Trace [HybrisUtils] Loaded OS library libz.so.1
17:37:19 Info  [Launcher] Creating window
17:37:19 Trace [Launcher] Loading Minecraft library
17:37:20 Info  [Launcher] Loaded Minecraft library
17:37:20 Debug [Launcher] Minecraft is at offset 0xac96b000
17:37:20 Trace [AppPlatform] Vtable size = 288
17:37:20 Trace [Patch] Patching - original: 85 83 87 86 129
17:37:20 Trace [Patch] Patching - result: 233 165 87 85 87
17:37:20 Trace [Patch] Patching - original: 85 83 87 86 131
17:37:20 Trace [Patch] Patching - result: 233 126 43 77 87
17:37:20 Warn  [Launcher] Android stub called
17:37:20 Warn  [Launcher] Android stub called
17:37:20 Warn  [Launcher] Android stub called
17:37:20 Warn  [Launcher] Android stub called
17:37:20 Warn  [Launcher] Android stub called
17:37:20 Info  [Minecraft] android_main starting. internalDataPath is './idata/', externalDataPath is './edata/'
17:37:20 Info  [Minecraft] NO LOG FILE! - AppPlatform_android::setStorageDirectory - using External dir - CurrentFileStoragePath is now '/home/momo/games/mcpe-1.13.1.5/'
17:37:20 Error [JNIVM] Object not found in current local layer
17:37:20 Debug [HttpCallStaticGlue] Successfully registerered HttpCall methods
17:37:20 Error [JNIVM] Object not found in current local layer
17:37:20 Debug [XSAPI.Android] Successfully registerered HttpCall methods
17:37:20 Error [JNIVM] Object not found in current local layer
17:37:20 Debug [HttpCallStaticGlue] Successfully registerered HttpCall methods
17:37:20 Error [JNIVM] Object not found in current local layer
17:37:20 Debug [XboxLiveAppConfig] Successfully registerered XboxLiveAppConfig methods
17:37:20 Error [JNIVM] Object not found in current local layer
17:37:20 Debug [XSAPI.Android] Successfully registerered HttpCall tcuiMethods
17:37:20 Trace [XBOXLive] Reading xbox config file
17:37:20 Warn  [Launcher] Android stub called
17:37:20 Warn  [Launcher] EGL stub eglMakeCurrent called
17:37:20 Warn  [Launcher] EGL stub eglMakeCurrent called
17:37:20 Warn  [Launcher] Android stub called
17:37:20 Warn  [Launcher] EGL stub eglMakeCurrent called
17:37:20 Warn  [Minecraft] NO LOG FILE! - [Device Lost] The graphics context was gained
17:37:20 Warn  [Minecraft] MinecraftGame::init && MinecraftGame::setSize!
17:37:20 Info  [Minecraft] NO LOG FILE! - IPv4 supported, port: 35351
17:37:20 Info  [Minecraft] NO LOG FILE! - IPv6 supported, port: 43993
17:37:38 Info  [Minecraft] NO LOG FILE! - IPv4 supported, port: 52650
17:37:38 Info  [Minecraft] NO LOG FILE! - IPv6 supported, port: 52121
