### ISSUE TITLE
The game just freezes and closes (1.14.30.2)

### ISSUE THREAD

**Issue by pimentelleo** [ChristopherHX/mcpelauncher-manifest#54]
leonardo@leonardo-desktop:~/mcpelauncher/build$ ~/mcpelauncher/build/mcpelauncher-client/mcpelauncher-client -dg ~/.local/share/mcpelauncher/versions/1.14.30.2/
03:13:42 Info  [Launcher] Version: client 7c17ac3 / manifest 74ceeb3
03:13:42 Info  [Launcher] CPU: GenuineIntel         Intel(R) Core(TM) i5-3330 CPU @ 3.00GHz
03:13:42 Info  [Launcher] CPU supports SSSE3: YES
03:13:42 Trace [Launcher] Loading hybris libraries
03:13:42 Trace [HybrisUtils] Loaded OS library /home/leonardo/mcpelauncher/mcpelauncher-linux-bin/libs/native/libfmod.so.9.16
03:13:42 Trace [HybrisUtils] Loaded OS library libm.so.6
03:13:42 Trace [HybrisUtils] Loaded OS library libz.so.1
03:13:42 Info  [Launcher] Creating window
03:13:42 Trace [Launcher] Loading gamepad mappings: /home/leonardo/mcpelauncher/build/gamecontrollerdb/gamecontrollerdb.txt
03:13:42 Trace [Launcher] Loading gamepad mappings: /usr/local/share/mcpelauncher/gamecontrollerdb.txt
03:13:42 Trace [Launcher] Loading Minecraft library
03:13:43 Info  [Launcher] Loaded Minecraft library
03:13:43 Debug [Launcher] Minecraft is at offset 0xee0c1000
03:13:43 Trace [AppPlatform] Vtable size = 295
03:13:43 Trace [Patch] Patching - original: 85 83 87 86 129
03:13:43 Trace [Patch] Patching - result: 233 103 253 26 100
03:13:43 Trace [Patch] Patching - original: 85 83 87 86 131
03:13:43 Trace [Patch] Patching - result: 233 188 118 19 100
03:13:43 Warn  [Launcher] Android stub called
03:13:43 Warn  [Launcher] Android stub called
03:13:43 Warn  [Launcher] Android stub called
03:13:43 Warn  [Launcher] Android stub called
03:13:43 Warn  [Launcher] Android stub called
03:13:43 Info  [Minecraft] android_main starting. internalDataPath is './idata/', externalDataPath is './edata/'
03:13:43 Info  [Minecraft] NO LOG FILE! - AppPlatform_android::setStorageDirectory - using External dir - CurrentFileStoragePath is now '/home/leonardo/.local/share/mcpelauncher/'
03:13:43 Error [JNIVM] Object not found in current local layer
03:13:43 Debug [HttpCallStaticGlue] Successfully registerered HttpCall methods
03:13:43 Error [JNIVM] Object not found in current local layer
03:13:43 Debug [XSAPI.Android] Successfully registerered HttpCall methods
03:13:43 Error [JNIVM] Object not found in current local layer
03:13:43 Debug [HttpCallStaticGlue] Successfully registerered HttpCall methods
03:13:43 Error [JNIVM] Object not found in current local layer
03:13:43 Debug [XboxLiveAppConfig] Successfully registerered XboxLiveAppConfig methods
03:13:43 Error [JNIVM] Object not found in current local layer
03:13:43 Debug [XSAPI.Android] Successfully registerered HttpCall tcuiMethods
03:13:43 Trace [XBOXLive] Reading xbox config file
03:13:43 Warn  [Launcher] Android stub called
03:13:43 Warn  [Launcher] EGL stub eglMakeCurrent called
03:13:43 Warn  [Launcher] EGL stub eglMakeCurrent called
03:13:43 Warn  [Launcher] Android stub called
03:13:43 Warn  [Launcher] EGL stub eglMakeCurrent called
03:13:43 Warn  [Minecraft] NO LOG FILE! - [Device Lost] The graphics context was gained
03:13:43 Warn  [Minecraft] MinecraftGame::init && MinecraftGame::setSize!
03:13:43 Info  [Minecraft] NO LOG FILE! - IPv4 supported, port: 47622
03:13:43 Info  [Minecraft] NO LOG FILE! - IPv6 supported, port: 49364
03:13:44 Debug [XSAPI.Android] sign_in_impl: will NOT be showing UI
03:13:44 Info  [com::microsoft::xbox::idp::interop::Interop::LogTelemetrySignIn] API - signin_silently - :Entering
03:13:44 Trace [DaemonLauncher] Starting daemon: /usr/local/bin/msa-daemon
03:13:44 Info  [com::microsoft::xbox::idp::interop::Interop::LogTelemetrySignIn] API - signin_silently - :Exiting
03:13:49 Info  [Minecraft] NO LOG FILE! - IPv4 supported, port: 44807
03:13:49 Info  [Minecraft] NO LOG FILE! - IPv6 supported, port: 48701
03:14:00 Info  [Minecraft] NO LOG FILE! - IPv4 supported, port: 39274
03:14:00 Info  [Minecraft] NO LOG FILE! - IPv6 supported, port: 49172
03:14:00 Info  [Minecraft] NO LOG FILE! - IPv4 supported, port: 19132
03:14:00 Info  [Minecraft] NO LOG FILE! - IPv6 supported, port: 19133
03:14:00 Info  [Minecraft] NO LOG FILE! - Player connected: batimenperverso, xuid: 2533275038807651
Signal 11 received
Backtrace elements: 6
#0 /home/leonardo/mcpelauncher/build/mcpelauncher-client/mcpelauncher-client(_ZN12CrashHandler12handleSignalEiPv+0xc9) [0x5684a4cf]
#1 linux-gate.so.1(__kernel_sigreturn+0) [0xf7f56b60]
#2 HYBRIS (null)+-258796077 in libminecraftpe.so+0x28705d3 [0xf09315d3]
#3 [0x1]
#4 HYBRIS (null)+-258712096 in libminecraftpe.so+0x2884de0 [0xf0945de0]
#5 [0x90909090]
Dumping stack...
#2 HYBRIS (null)+-179033852 in libminecraftpe.so+0x7481904 [0xf5542904]
#13 HYBRIS (null)+-301199360 in libminecraftpe.so+0x0000 [0xee0c1000]
#18 HYBRIS (null)+-258796077 in libminecraftpe.so+0x28705d3 [0xf09315d3]
#20 HYBRIS (null)+-258712096 in libminecraftpe.so+0x2884de0 [0xf0945de0]
#30 HYBRIS (null)+-179033852 in libminecraftpe.so+0x7481904 [0xf5542904]
#32 HYBRIS (null)+-251416795 in libminecraftpe.so+0x2f79f25 [0xf103af25]
#80 HYBRIS (null)+-179033852 in libminecraftpe.so+0x7481904 [0xf5542904]
#94 HYBRIS (null)+-179033852 in libminecraftpe.so+0x7481904 [0xf5542904]
#100 HYBRIS (null)+-258796077 in libminecraftpe.so+0x28705d3 [0xf09315d3]
#108 HYBRIS (null)+-251308515 in libminecraftpe.so+0x2f9461d [0xf105561d]
#112 HYBRIS (null)+-251308600 in libminecraftpe.so+0x2f945c8 [0xf10555c8]
#115 HYBRIS (null)+-179033852 in libminecraftpe.so+0x7481904 [0xf5542904]
#116 HYBRIS (null)+-251444887 in libminecraftpe.so+0x2f73169 [0xf1034169]
#120 HYBRIS (null)+-252940052 in libminecraftpe.so+0x2e060ec [0xf0ec70ec]
#123 HYBRIS (null)+-179033852 in libminecraftpe.so+0x7481904 [0xf5542904]
#124 HYBRIS (null)+-252965747 in libminecraftpe.so+0x2dffc8d [0xf0ec0c8d]
#128 HYBRIS (null)+-252965783 in libminecraftpe.so+0x2dffc69 [0xf0ec0c69]
#129 HYBRIS (null)+-179033852 in libminecraftpe.so+0x7481904 [0xf5542904]
#130 HYBRIS (null)+-179033852 in libminecraftpe.so+0x7481904 [0xf5542904]
#132 HYBRIS (null)+-260000238 in libminecraftpe.so+0x274a612 [0xf080b612]
#136 HYBRIS (null)+-260002097 in libminecraftpe.so+0x2749ecf [0xf080aecf]
#138 HYBRIS (null)+-179033852 in libminecraftpe.so+0x7481904 [0xf5542904]
#139 HYBRIS (null)+-178671788 in libminecraftpe.so+0x74d9f54 [0xf559af54]
#140 HYBRIS (null)+-251444887 in libminecraftpe.so+0x2f73169 [0xf1034169]
#145 HYBRIS (null)+-178671768 in libminecraftpe.so+0x74d9f68 [0xf559af68]
#148 HYBRIS (null)+-251434660 in libminecraftpe.so+0x2f7595c [0xf103695c]
#178 HYBRIS (null)+-179033852 in libminecraftpe.so+0x7481904 [0xf5542904]
#186 HYBRIS (null)+-179033852 in libminecraftpe.so+0x7481904 [0xf5542904]
#188 HYBRIS (null)+-251339067 in libminecraftpe.so+0x2f8cec5 [0xf104dec5]
#192 HYBRIS (null)+-259865460 in libminecraftpe.so+0x276b48c [0xf082c48c]
#214 HYBRIS (null)+-179033852 in libminecraftpe.so+0x7481904 [0xf5542904]
#216 HYBRIS (null)+-263254277 in libminecraftpe.so+0x242fefb [0xf04f0efb]
#218 HYBRIS operator delete(void*)+6 in libminecraftpe.so+0x5608c36 [0xf36c9c36]
#219 HYBRIS (null)+-179033852 in libminecraftpe.so+0x7481904 [0xf5542904]
#220 HYBRIS (null)+-263242676 in libminecraftpe.so+0x2432c4c [0xf04f3c4c]
#223 HYBRIS (null)+-179033852 in libminecraftpe.so+0x7481904 [0xf5542904]
#224 HYBRIS (null)+-263250220 in libminecraftpe.so+0x2430ed4 [0xf04f1ed4]
#236 HYBRIS (null)+-263250479 in libminecraftpe.so+0x2430dd1 [0xf04f1dd1]
#243 HYBRIS (null)+-179033852 in libminecraftpe.so+0x7481904 [0xf5542904]
#244 HYBRIS (null)+-263261797 in libminecraftpe.so+0x242e19b [0xf04ef19b]
#248 HYBRIS (null)+-263261876 in libminecraftpe.so+0x242e14c [0xf04ef14c]
#252 HYBRIS (null)+-263235603 in libminecraftpe.so+0x24347ed [0xf04f57ed]
#254 HYBRIS (null)+-179033852 in libminecraftpe.so+0x7481904 [0xf5542904]
#255 HYBRIS (null)+-179033852 in libminecraftpe.so+0x7481904 [0xf5542904]
#256 HYBRIS (null)+-263268597 in libminecraftpe.so+0x242c70b [0xf04ed70b]
#267 HYBRIS (null)+-179033852 in libminecraftpe.so+0x7481904 [0xf5542904]
#272 HYBRIS (null)+-210645234 in libminecraftpe.so+0x565bf0e [0xf371cf0e]
#299 HYBRIS (null)+-210645234 in libminecraftpe.so+0x565bf0e [0xf371cf0e]
#404 HYBRIS (null)+-251443269 in libminecraftpe.so+0x2f737bb [0xf10347bb]
#406 HYBRIS (null)+-179033852 in libminecraftpe.so+0x7481904 [0xf5542904]
#408 HYBRIS (null)+-251308515 in libminecraftpe.so+0x2f9461d [0xf105561d]
#412 HYBRIS (null)+-251443269 in libminecraftpe.so+0x2f737bb [0xf10347bb]
#506 HYBRIS (null)+-179033852 in libminecraftpe.so+0x7481904 [0xf5542904]
#507 HYBRIS (null)+-179033852 in libminecraftpe.so+0x7481904 [0xf5542904]
#508 HYBRIS (null)+-258796146 in libminecraftpe.so+0x287058e [0xf093158e]
#522 HYBRIS (null)+-248426202 in libminecraftpe.so+0x3254126 [0xf1315126]
#542 HYBRIS (null)+-248578426 in libminecraftpe.so+0x322ee86 [0xf12efe86]
#544 HYBRIS (null)+-258778666 in libminecraftpe.so+0x28749d6 [0xf09359d6]
#547 HYBRIS (null)+-178665512 in libminecraftpe.so+0x74db7d8 [0xf559c7d8]
#548 HYBRIS (null)+-258778741 in libminecraftpe.so+0x287498b [0xf093598b]
#562 HYBRIS (null)+-179033852 in libminecraftpe.so+0x7481904 [0xf5542904]
#564 HYBRIS (null)+-258693628 in libminecraftpe.so+0x2889604 [0xf094a604]
#574 HYBRIS (null)+-179033852 in libminecraftpe.so+0x7481904 [0xf5542904]
#576 HYBRIS (null)+-261105029 in libminecraftpe.so+0x263ca7b [0xf06fda7b]
#584 HYBRIS (null)+-250887320 in libminecraftpe.so+0x2ffb368 [0xf10bc368]
#595 HYBRIS (null)+-178693516 in libminecraftpe.so+0x74d4a74 [0xf5595a74]
#601 HYBRIS (null)+-261105712 in libminecraftpe.so+0x263c7d0 [0xf06fd7d0]
#602 HYBRIS (null)+-179033852 in libminecraftpe.so+0x7481904 [0xf5542904]
#604 HYBRIS (null)+-250887132 in libminecraftpe.so+0x2ffb424 [0xf10bc424]
#607 HYBRIS (null)+-179033852 in libminecraftpe.so+0x7481904 [0xf5542904]
#611 HYBRIS (null)+-179033852 in libminecraftpe.so+0x7481904 [0xf5542904]
#612 HYBRIS (null)+-250950056 in libminecraftpe.so+0x2febe58 [0xf10ace58]
#619 HYBRIS (null)+-178589260 in libminecraftpe.so+0x74ee1b4 [0xf55af1b4]
#625 HYBRIS (null)+-178589240 in libminecraftpe.so+0x74ee1c8 [0xf55af1c8]
#639 HYBRIS (null)+-250887120 in libminecraftpe.so+0x2ffb430 [0xf10bc430]
#640 HYBRIS (null)+-250887200 in libminecraftpe.so+0x2ffb3e0 [0xf10bc3e0]
#643 HYBRIS (null)+-250887296 in libminecraftpe.so+0x2ffb380 [0xf10bc380]
#644 HYBRIS (null)+-250887520 in libminecraftpe.so+0x2ffb2a0 [0xf10bc2a0]
#647 HYBRIS (null)+-250887616 in libminecraftpe.so+0x2ffb240 [0xf10bc240]
#648 HYBRIS (null)+-250887680 in libminecraftpe.so+0x2ffb200 [0xf10bc200]
#658 HYBRIS (null)+-179033852 in libminecraftpe.so+0x7481904 [0xf5542904]
#660 HYBRIS (null)+-261118017 in libminecraftpe.so+0x26397bf [0xf06fa7bf]
#664 HYBRIS (null)+-210683285 in libminecraftpe.so+0x5652a6b [0xf3713a6b]
#674 HYBRIS (null)+-179033852 in libminecraftpe.so+0x7481904 [0xf5542904]
#676 HYBRIS (null)+-241867852 in libminecraftpe.so+0x38953b4 [0xf19563b4]
#679 HYBRIS (null)+-179033852 in libminecraftpe.so+0x7481904 [0xf5542904]
#680 HYBRIS (null)+-248586923 in libminecraftpe.so+0x322cd55 [0xf12edd55]
#682 HYBRIS (null)+-178585408 in libminecraftpe.so+0x74ef0c0 [0xf55b00c0]
#687 HYBRIS (null)+-178925568 in libminecraftpe.so+0x749c000 [0xf555d000]
#688 HYBRIS (null)+-178585476 in libminecraftpe.so+0x74ef07c [0xf55b007c]
#689 HYBRIS (null)+-178585584 in libminecraftpe.so+0x74ef010 [0xf55b0010]
#690 HYBRIS (null)+-178674080 in libminecraftpe.so+0x74d9660 [0xf559a660]
#691 HYBRIS (null)+-178585396 in libminecraftpe.so+0x74ef0cc [0xf55b00cc]
#692 HYBRIS (null)+-178585408 in libminecraftpe.so+0x74ef0c0 [0xf55b00c0]
#693 HYBRIS (null)+-178585416 in libminecraftpe.so+0x74ef0b8 [0xf55b00b8]
#695 HYBRIS (null)+-210362644 in libminecraftpe.so+0x56a0eec [0xf3761eec]
#696 HYBRIS (null)+-288597008 in libminecraftpe.so+0xc04bf0 [0xeecc5bf0]
#699 HYBRIS (null)+-178585408 in libminecraftpe.so+0x74ef0c0 [0xf55b00c0]
#711 HYBRIS (null)+-209839939 in libminecraftpe.so+0x57208bd [0xf37e18bd]
#712 HYBRIS (null)+-209839953 in libminecraftpe.so+0x57208af [0xf37e18af]
#724 HYBRIS (null)+-179033852 in libminecraftpe.so+0x7481904 [0xf5542904]
#728 HYBRIS getTimeMs()+38 in libminecraftpe.so+0x3e49c86 [0xf1f0ac86]
#736 HYBRIS (null)+-210683285 in libminecraftpe.so+0x5652a6b [0xf3713a6b]
#739 HYBRIS (null)+-179033852 in libminecraftpe.so+0x7481904 [0xf5542904]
#740 HYBRIS std::_Function_handler<int (), int (*)()>::_M_invoke(std::_Any_data const&)+22 in libminecraftpe.so+0xc3d946 [0xeecfe946]
#741 HYBRIS (null)+-178585476 in libminecraftpe.so+0x74ef07c [0xf55b007c]
#750 HYBRIS (null)+-179033852 in libminecraftpe.so+0x7481904 [0xf5542904]
#752 HYBRIS (null)+-261130811 in libminecraftpe.so+0x26365c5 [0xf06f75c5]
#757 HYBRIS operator new(unsigned int)+12 in libminecraftpe.so+0x560af0c [0xf36cbf0c]
#758 HYBRIS operator delete(void*)+6 in libminecraftpe.so+0x5608c36 [0xf36c9c36]
#760 HYBRIS (null)+-179033852 in libminecraftpe.so+0x7481904 [0xf5542904]
#764 HYBRIS operator delete(void*)+28 in libminecraftpe.so+0x5608c4c [0xf36c9c4c]
#767 HYBRIS (null)+-179033852 in libminecraftpe.so+0x7481904 [0xf5542904]
#768 HYBRIS (null)+-255273486 in libminecraftpe.so+0x2bcc5f2 [0xf0c8d5f2]
#770 HYBRIS operator delete(void*)+6 in libminecraftpe.so+0x5608c36 [0xf36c9c36]
#771 HYBRIS (null)+-179033852 in libminecraftpe.so+0x7481904 [0xf5542904]
#772 HYBRIS (null)+-255269873 in libminecraftpe.so+0x2bcd40f [0xf0c8e40f]
#779 HYBRIS (null)+-178693556 in libminecraftpe.so+0x74d4a4c [0xf5595a4c]
#780 HYBRIS (null)+-255272759 in libminecraftpe.so+0x2bcc8c9 [0xf0c8d8c9]
#781 HYBRIS (null)+-178693624 in libminecraftpe.so+0x74d4a08 [0xf5595a08]
#790 HYBRIS (null)+-179033852 in libminecraftpe.so+0x7481904 [0xf5542904]
#792 HYBRIS (null)+-261123270 in libminecraftpe.so+0x263833a [0xf06f933a]
#806 HYBRIS (null)+-288189660 in libminecraftpe.so+0xc68324 [0xeed29324]
#808 HYBRIS (null)+-261122576 in libminecraftpe.so+0x26385f0 [0xf06f95f0]
#822 HYBRIS (null)+-179033852 in libminecraftpe.so+0x7481904 [0xf5542904]
#824 HYBRIS (null)+-210613569 in libminecraftpe.so+0x5663abf [0xf3724abf]
#828 HYBRIS (null)+-210613608 in libminecraftpe.so+0x5663a98 [0xf3724a98]
Abortado (imagem do núcleo gravada)

**Comment by ChristopherHX** [comment]
IDK, on my PC's it won't crash, every CPU / GPU is different. The log tells me nothing more, than that you are using **unstable** xboxlive and the game crashes somewhere on your pc.
BTW I declared random crashes as a feature in the readme, retry starting it or goback to the original (from minecraft-linux) @1.14.1.5.

**Comment by pimentelleo** [comment]
Uhmmm okay, i was using the original MSA from the original minecraft-linux project for log on my microsoft account. 
Will try another version, another msa build

**Comment by blastermaster77** [comment]
i have the same problem, it loads-up fine the world, as soon I hit W to start walking it crashes all the tme with the exact error log as above.

**Comment by blastermaster77** [comment]
I can confirm that if you use the keyboard to control the game it crashes, with the gamepad it does not.

**Comment by ChristopherHX** [comment]
What OS, older linux versions are way to buggy like 16.04
I believe you cannot say it **exact** the same log, without proving it.

**Comment by blastermaster77** [comment]
> What OS, older linux versions are way to buggy like 16.04
> I believe you cannot say it **exact** the same log, without proving it.

now its working weird!

**Comment by ChristopherHX** [comment]
ubuntu 19.10, was proven to be unstable. X11 ime or xim module crashes 
Crash reason not worth the effort
