### ISSUE TITLE
Crashes immediately with exit code 127

### ISSUE THREAD

**Issue by lsdxm** [ChristopherHX/mcpelauncher-manifest#56]
/tmp/.mount_MinecrAgeoSb/usr/bin/./mcpelauncher-client: error while loading shared libraries: libEGL.so.1: cannot open shared object file: No such file or directory
Process exited with unexpected exit code: 127

**Comment by ChristopherHX** [comment]
**Please read the description**
https://github.com/ChristopherHX/linux-packaging-scripts/releases/tag/appimage

```For Debian based x86_64 you might need to install these sudo dpkg --add-architecture i386 && sudo apt-get update && sudo apt install libc6-i386 libegl1-mesa:i386 zlib1g:i386 libstdc++6:i386 libgl1-mesa-dri:i386 libasound2:i386 pulseaudio, for archlinux enable Multilib then install sudo pacman -Sy && sudo pacman -S lib32-mesa lib32-libpulse lib32-alsa-plugins for other distro figure it out```

If you are not on debian / ubuntu / arch / manjaro
install 32bit libegl (also known as mesa or mesa3d from https://www.mesa3d.org/) or better switch to a better supported distro

**Comment by ChristopherHX** [comment]
Crash reason not worth the effort
