### ISSUE TITLE
Doesn't fit screen

### ISSUE THREAD

**Issue by jesyiahh** [ChristopherHX/mcpelauncher-manifest#57]
Minecraft opens but does not fit screen.

**Comment by ChristopherHX** [comment]
Please elaborate or it will be closed soon.
What OS? (Linux or macOS is too generic)
What GPU?
Which GPU DRIVER (mesa(3d)) Version?
Which binary or artifact from what download link, do you downloaded?
Which Minecraft Bedrock (PE) Version?

**Comment by ChristopherHX** [comment]
Insufficient Information.
Please reopen, if you know my questions or keep it closed.
Your 32bit GPU drivers are defect.
