### ISSUE TITLE
Installed package dependencies, still crashes with exit code 127

### ISSUE THREAD

**Issue by mreuler42** [ChristopherHX/mcpelauncher-manifest#58]
On Ubuntu 16.04 LTS x86_64, just did a hard wipe and reinstall. Using the Minecraft_Bedrock_Launcher-8f370fe-x86_64.AppImage

ran `sudo dpkg --add-architecture i386 && sudo apt-get update && sudo apt install libc6-i386 libegl1-mesa:i386 zlib1g:i386 libstdc++6:i386 libgl1-mesa-dri:i386 libasound2:i386 pulseaudio`

`libasound2:i386 is already the newest version (1.1.0-0ubuntu1).
libc6-i386 is already the newest version (2.23-0ubuntu11).
pulseaudio is already the newest version (1:8.0-0ubuntu3.10).
libegl1-mesa:i386 is already the newest version (18.0.5-0ubuntu0~16.04.1).
libgl1-mesa-dri:i386 is already the newest version (18.0.5-0ubuntu0~16.04.1).
libstdc++6:i386 is already the newest version (5.4.0-6ubuntu1~16.04.12).
zlib1g:i386 is already the newest version (1:1.2.8.dfsg-2ubuntu4.3).`

Get this error code:
/tmp/.mount_Minecr4mCsZ5/usr/bin/./mcpelauncher-client: error while loading shared libraries: libX11.so.6: cannot open shared object file: No such file or directory
Process exited with unexpected exit code: 127

**Comment by ChristopherHX** [comment]
Well I'm not perfect, you know 16.04 is very old and not active supported by me.
Missing dependency libX11.so.6 => https://packages.debian.org/search?searchon=contents&keywords=libX11.so.6&mode=path&suite=stable&arch=any

debian.org search tells me, please install `libx11-6:i386`

Please use the linked website to resolve further error, please tell me if there are more missing deps, to fix the documentation

**Comment by mreuler42** [comment]
Fix worked, thanks, I appreciate it.

**Comment by SaturnSoftware** [comment]
i had this issue in  a clean install of 19.10
