### ISSUE TITLE
visual bug with rain in 1.16.0.51

### ISSUE THREAD

**Issue by teh404guy** [ChristopherHX/mcpelauncher-manifest#59]
a visual bug turning rain into randomly sized polygonal shapes
symptoms: lag, lag, and lag
![Capture d’écran du 2020-03-21 20-03-06](https://user-images.githubusercontent.com/62482190/77234675-9ebfaf80-6bb0-11ea-88c0-c3ba254ee760.png)

MCPE version: 1.16.0.51
OS: MANJARO LINUX (archlinux based)
Architecture: X86-64
CPU: intel core i5
GPU: AMD CAICOS 1024MB
OEM: HP

**Comment by ChristopherHX** [comment]
Its just a Beta of Minecraft, don't expect stability.
Dive into water and it will crash.

**Comment by teh404guy** [comment]
so is it a client thing or mcpe acting up 
since in my phone the rain is normal

**Comment by ChristopherHX** [comment]
On my PC with intel uhd
![Bildschirmfoto vom 2020-03-21 21-35-34](https://user-images.githubusercontent.com/44845461/77236130-f879a700-6bbb-11ea-86c7-d62ced080e50.png)
 and i7, rain is just fine on 1.16.0.51. (no weird polygons)
Bugs with your specfic GPU (or gpu drivers), are out of scope of this launcher.

MCPE version: 1.16.0.51
OS: ubuntu 19.04
Architecture: X86-64 (game is x86 32bit)
CPU: intel core i7
GPU: Intel UHD Graphics 620
OEM: DELL

**Comment by ChristopherHX** [comment]
Fixing Minecraft Game / Render Bugs is not the aim of this launcher

**Comment by ChristopherHX** [comment]
Look at this issue, not a fault of this launcher
https://bugs.mojang.com/browse/MCPE-65518
