### ISSUE TITLE
Microsoft Account Wont Load

### ISSUE THREAD

**Issue by luciagcm** [ChristopherHX/mcpelauncher-manifest#62]
Every time i log in to my microsoft account it just keeps loading forever or tells me it failed to log me in

**Comment by ChristopherHX** [comment]
Please provide the game log, and follow the linked issue (make shure msa-daemon is running during login)
Duplicate of https://github.com/ChristopherHX/mcpelauncher-manifest/issues/42

**Comment by luciagcm** [comment]
where do i find the game log

**Comment by luciagcm** [comment]
also theres no linked issue

**Comment by luciagcm** [comment]
HI im sorry i dont code or anything idk how to do these things could you give me a step by step or video? im on a mac

**Comment by ChristopherHX** [comment]
BTW
- You need an xboxlive profile.
- Luck
- In the launcher upper right gear icon you will find a checkbox to show the log
- Try running `/Application/Minecraft\ Bedrock\ Launcher.app/Contents/MacOS/msa-daemon` in a Terminal, then try login (Do not close the Terminal before closing Minecraft)
- idk if the path is correct, might contains errors

**Comment by luciagcm** [comment]
Okay thank you! Ill try that

**Comment by DavidUnknown** [comment]
Hey! Hi
Could you please help me with the same but manjaro?
Xbox login not working
How i do to install msa daemon and activate it?
