### ISSUE TITLE
Sound is grabbed exclusively by launcher?

### ISSUE THREAD

**Issue by thijs** [ChristopherHX/mcpelauncher-manifest#63]
I'm not entirely sure if this is a problem with mcpelauncher, but it does seem so. With the other version (the one this one's forked from) I don't have this issue.
The problem is that when I'm in minecraft firefox seems unable to access the sound device. Youtube videos just freeze. As soon as I exit minecraft, the video starts playing.

**Comment by ChristopherHX** [comment]
But how can that happen?
When you have last tried the original one?
Maybe try uninstalling pulseaudio:i386 and install pulseaudio x64?

**Comment by thijs** [comment]
I've switched a couple of times in the last week. I'll look at the pulseaudio thing.
Maybe it's something completely different, as yesterday it suddenly did seem to work for a while. My setup is a little strange, as I run firefox in docker containers, so maybe that is messing things up.

**Comment by thijs** [comment]
Sorry for creating noise. This looks like it's something wrong with my setup. I haven't had the problem for the last day after I added a symlink in the run directory which mcpelauncher complained about at startup (but I think it's actually firefox running in docker that really needed it). Anyway, closing this now. Sorry again.
