### ISSUE TITLE
XboxLive: Couldn't get default nsal

### ISSUE THREAD

**Issue by EcstaticalEcstatic** [ChristopherHX/mcpelauncher-manifest#64]
XBL Sign-in worked a week or so ago, now fails on the same launcher AppImage build. 
```
Error [XboxLive] Sign in error: Couldn't get default nsal.
Info  [com::microsoft::xbox::idp::interop::Interop::LogTelemetrySignIn] API - signin - :Exiting - runtime_error
```
Clearing all MSA, minecraftlinux, and minecraft launcher data from .local and my minecraft data folder doesn't resolve the issue.

**Comment by ChristopherHX** [comment]
Couldn't get default nsal <=> Minecraft cannot connect to Xbox live
Proxies will break it for now

**Comment by EcstaticalEcstatic** [comment]
Wasn't a proxy, it seems this issue also affects other network routing configurations. In my case it was unable to connect to XBL over a bridge, even on the same subnet as the router.
