### ISSUE TITLE
Cannot Install mcpelauncher-client.deb for Ubuntu 18.04

### ISSUE THREAD

**Issue by Breece1019** [ChristopherHX/mcpelauncher-manifest#66]
I am unable to install both the client and the core .deb files for Ubuntu.  When installing, it will simply stop, and then continue to show the "install" button.  When I tried to launch Minecraft anyways, I get an internal error message from Ubuntu saying that the mcpelauncher-client is not installed.

**Comment by Breece1019** [comment]
I see that you have listed that the .deb files will not work, but is there any way to manually install them?  Where do I put them?

**Comment by ChristopherHX** [comment]
Please don't use the .deb's use the appimage (make it executable and eun the file).
You can install the deb's with double click.
mcpelauncher-core first then all others.
