### ISSUE TITLE
Can't use 256x version of BDcraft texture packs

### ISSUE THREAD

**Issue by dylanparry** [ChristopherHX/mcpelauncher-manifest#67]
I'm trying to use the 256x version of BDCraft's VanillaBDcraft texture pack on my laptop, which has 32GB RAM and is running Arch Linux. I'm using the AppImage for the launcher.

BDcraft appear to be using some code to detect whether there's enough RAM on the machine to support the different resolutions that they offer. It tells me that I don't have enough memory to use the 256x, but only the 128x. I'm told that the 256x version requires 8GB RAM, which I clearly have far more than.

Is there something in this project that is setting the amount of RAM that's available to the game, or is a case that it's misreporting the amount of available RAM?

**Comment by Mhowser** [comment]
Probably the game itself since it is 32bit.

**Comment by dylanparry** [comment]
That could well be the reason!

**Comment by Mhowser** [comment]
Minecraft will have a 64bit release soon, so stay tuned

**Comment by dylanparry** [comment]
I hope so :) Thanks. I'll wait until that day finally comes and try it again then.
