### ISSUE TITLE
exit code 6 (appimage)

### ISSUE THREAD

**Issue by Gustavekkj** [ChristopherHX/mcpelauncher-manifest#69]
00:20:45 Info  [Launcher] Version: client 7c17ac3 / manifest 45f9d98
00:20:45 Info  [Launcher] CPU: GenuineIntel Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz
00:20:45 Info  [Launcher] CPU supports SSSE3: YES
00:20:45 Trace [Launcher] Loading hybris libraries
00:20:45 Trace [HybrisUtils] Loaded OS library /tmp/.mount_MinecrxF93Cq/usr/share/mcpelauncher/libs/native/libfmod.so.9.16
00:20:45 Trace [HybrisUtils] Loaded OS library libm.so.6
00:20:45 Trace [HybrisUtils] Loaded OS library libz.so.1
00:20:45 Info  [Launcher] Creating window
00:20:45 Trace [Launcher] Loading gamepad mappings: /tmp/.mount_MinecrxF93Cq/usr/share/mcpelauncher/gamecontrollerdb.txt
00:20:45 Trace [Launcher] Loading Minecraft library
linkerSignal 6 received
Backtrace elements: 13
#0 /tmp/.mount_MinecrxF93Cq/usr/bin/./mcpelauncher-client(_ZN12CrashHandler12handleSignalEiPv+0xb7) [0x8325aa5]
#1 linux-gate.so.1(__kernel_sigreturn+0) [0xf7f92b60]
#2 linux-gate.so.1(__kernel_vsyscall+0x9) [0xf7f92b49]
#3 /lib/i386-linux-gnu/libc.so.6(gsignal+0xc6) [0xf78ba4c6]
#4 /lib/i386-linux-gnu/libc.so.6(abort+0x130) [0xf78a23f7]
#5 /lib/i386-linux-gnu/libstdc++.so.6(+0x7db54) [0xf7c39b54]
#6 /lib/i386-linux-gnu/libstdc++.so.6(+0x8bdd8) [0xf7c47dd8]
#7 /lib/i386-linux-gnu/libstdc++.so.6(+0x8be61) [0xf7c47e61]
#8 /lib/i386-linux-gnu/libstdc++.so.6(__cxa_rethrow+0) [0xf7c481a0]
#9 /tmp/.mount_MinecrxF93Cq/usr/bin/./mcpelauncher-client(_ZN14MinecraftUtils16loadMinecraftLibERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE+0x14c) [0x8326be8]
#10 /tmp/.mount_MinecrxF93Cq/usr/bin/./mcpelauncher-client(main+0x15d0) [0x82b5dce]
#11 /lib/i386-linux-gnu/libc.so.6(__libc_start_main+0xf5) [0xf78a3ee5]
#12 /tmp/.mount_MinecrxF93Cq/usr/bin/./mcpelauncher-client() [0x82b3381]
Dumping stack...
Process exited with unexpected exit code: 6

**Comment by ChristopherHX** [comment]
After some research please refer to this solution
https://github.com/ChristopherHX/mcpelauncher-manifest/issues/78#issuecomment-617794215
I wasn't shure, because of the difference between the errors, e.g. your log doesn't contains the full error Message
