### ISSUE TITLE
Crash - Process exited with unexpected exit code: 6

### ISSUE THREAD

**Issue by edubr029** [ChristopherHX/mcpelauncher-manifest#79]
23:26:19 Info  [Launcher] Version: client c735370 / manifest b3dd620
23:26:19 Info  [Launcher] CPU: GenuineIntel       Intel(R) Atom(TM) x5-Z8350  CPU @ 1.44GHz
23:26:19 Info  [Launcher] CPU supports SSSE3: YES
23:26:19 Trace [Launcher] Loading hybris libraries
23:26:19 Trace [HybrisUtils] Loaded OS library /usr/share/mcpelauncher/libs/native/libfmod.so.9.16
23:26:19 Trace [HybrisUtils] Loaded OS library libm.so.6
23:26:19 Trace [HybrisUtils] Loaded OS library libz.so.1
23:26:19 Trace [Launcher] Loading Minecraft library
23:26:21 Info  [Launcher] Loaded Minecraft library
23:26:21 Debug [Launcher] Minecraft is at offset 0xec034000
23:26:21 Trace [Launcher] Initializing vtables
23:26:21 Error [MinecraftSymbols] Unresolved symbol: _ZN3App4initER10AppContext
23:26:21 Error [MinecraftSymbols] Unresolved vtable symbol: _ZN3App4quitERKSsS1_
23:26:21 Error [MinecraftSymbols] Unresolved vtable symbol: _ZN3App6updateEv
23:26:21 Error [MinecraftSymbols] Unresolved vtable symbol: _ZN3App16setRenderingSizeEii
23:26:21 Error [MinecraftSymbols] Unresolved vtable symbol: _ZN3App17setUISizeAndScaleEiif
23:26:21 Error [MinecraftSymbols] Unresolved vtable symbol: _ZN3App10wantToQuitEv
23:26:21 Error [MinecraftSymbols] Unresolved symbol: _ZN14ServiceLocatorI11AppPlatformE15mDefaultServiceE
23:26:21 Error [MinecraftSymbols] Unresolved symbol: _ZN11AppPlatform12showKeyboardERKSsibbbiRKN3glm5tvec2IfLNS2_9precisionE0EEE
23:26:21 Error [MinecraftSymbols] Unresolved symbol: _ZNK11AppPlatform22getHardwareInformationEv
23:26:21 Error [MinecraftSymbols] Unresolved symbol: _ZN17AppResourceLoaderC1ESt8functionIFN4Core10PathBufferISsEEvEE
23:26:21 Error [MinecraftSymbols] Unresolved symbol: _ZN10Automation16AutomationClientC2ER13IMinecraftApp
23:26:21 Error [MinecraftSymbols] Unresolved symbol: _ZN14ClientInstance7getUserEv
23:26:21 Error [MinecraftSymbols] Unresolved symbol: _ZN14ClientInstance15_startLeaveGameEv
23:26:21 Error [MinecraftSymbols] Unresolved symbol: _ZN14ClientInstance16_syncDestroyGameEv
23:26:21 Error [MinecraftSymbols] Unresolved symbol: _ZNK13CommandOutput11getMessagesEv
23:26:21 Error [MinecraftSymbols] Unresolved symbol: _ZN19CommandOutputSender9translateERKSt6vectorISsSaISsEE
23:26:21 Error [MinecraftSymbols] Unresolved symbol: _ZN19CommandOutputSenderC2ERN10Automation16AutomationClientE
23:26:21 Error [MinecraftSymbols] Unresolved symbol: _ZN19CommandOutputSenderD2Ev
23:26:21 Error [MinecraftSymbols] Unresolved symbol: _ZN19CommandOutputSender4sendERK13CommandOriginRK13CommandOutput
23:26:21 Error [MinecraftSymbols] Unresolved symbol: _ZN19CommandOutputSender22registerOutputCallbackERKSt8functionIFvR19AutomationCmdOutputEE
23:26:21 Error [MinecraftSymbols] Unresolved symbol: _ZN6Common23getGameVersionStringNetEv
23:26:21 Error [MinecraftSymbols] Unresolved symbol: _ZN30ExternalFileLevelStorageSourceC2EPN4Core15FilePathManagerESt10shared_ptrI22SaveTransactionManagerE
23:26:21 Error [MinecraftSymbols] Unresolved symbol: _ZN30ExternalFileLevelStorageSource18createLevelStorageER9SchedulerRKSsRK15ContentIdentityRK19IContentKeyProvider
23:26:21 Error [MinecraftSymbols] Unresolved symbol: _ZN19ResourceLoadManagerC2Ev
23:26:21 Error [MinecraftSymbols] Unresolved symbol: _ZN19ResourceLoadManager4syncE16ResourceLoadType
23:26:21 Error [MinecraftSymbols] Unresolved symbol: _ZN4I18n3getERKSsRKSt6vectorISsSaISsEE
23:26:21 Error [MinecraftSymbols] Unresolved symbol: _ZN4I18n14chooseLanguageERKSs
23:26:21 Error [MinecraftSymbols] Unresolved symbol: _ZN4I18n13loadLanguagesER19ResourcePackManagerR19ResourceLoadManagerRKSs
23:26:21 Error [MinecraftSymbols] Unresolved symbol: _ZN5Level16createRandomSeedEv
23:26:21 Error [MinecraftSymbols] Unresolved symbol: _ZN13LevelSettingsC2Ev
23:26:21 Error [MinecraftSymbols] Unresolved symbol: _ZN13LevelSettingsC2ERKS_
23:26:21 Error [MinecraftSymbols] Unresolved symbol: _ZN13LevelSettings15parseSeedStringERKSsj
23:26:21 Error [MinecraftSymbols] Unresolved symbol: _ZN9Minecraft11getCommandsEv
23:26:21 Error [MinecraftSymbols] Unresolved symbol: _ZNK9Minecraft8getLevelEv
23:26:21 Error [MinecraftSymbols] Unresolved symbol: _ZN17MinecraftCommands15setOutputSenderESt10unique_ptrI19CommandOutputSenderSt14default_deleteIS1_EE
23:26:21 Error [MinecraftSymbols] Unresolved symbol: _ZNK17MinecraftCommands23requestCommandExecutionESt10unique_ptrI13CommandOriginSt14default_deleteIS1_EERKSsib
23:26:21 Error [MinecraftSymbols] Unresolved symbol: _ZN17MinecraftEventingC2ERKSs
23:26:21 Error [MinecraftSymbols] Unresolved symbol: _ZN17MinecraftEventing4initEv
23:26:21 Error [MinecraftSymbols] Unresolved symbol: _ZN13MinecraftGameC2EiPPc
23:26:21 Error [MinecraftSymbols] Unresolved symbol: _ZN13MinecraftGameD2Ev
23:26:21 Error [MinecraftSymbols] Unresolved symbol: _ZNK13MinecraftGame8isInGameEv
23:26:21 Error [MinecraftSymbols] Unresolved symbol: _ZN13MinecraftGame16requestLeaveGameEbb
23:26:21 Error [MinecraftSymbols] Unresolved symbol: _ZN13MinecraftGame24doPrimaryClientReadyWorkESt8functionIFvvEE
23:26:21 Error [MinecraftSymbols] Unresolved symbol: _ZN13MinecraftGame21getPrimaryUserOptionsEv
23:26:21 Error [MinecraftSymbols] Unresolved symbol: _ZN13MinecraftGame24getPrimaryClientInstanceEv
23:26:21 Error [MinecraftSymbols] Unresolved symbol: _ZN13MinecraftGame14startLeaveGameEv
23:26:21 Error [MinecraftSymbols] Unresolved symbol: _ZN13MinecraftGame17continueLeaveGameEv
23:26:21 Error [MinecraftSymbols] Unresolved symbol: _ZN13MinecraftGame14setTextboxTextERKSsi
23:26:21 Error [MinecraftSymbols] Unresolved symbol: _ZN20MinecraftScreenModel32navigateToXblConsoleSignInScreenERKSsS1_
23:26:21 Error [MinecraftSymbols] Unresolved symbol: _ZN20MinecraftScreenModel41navigateToXblConsoleSignInSucceededScreenERKN6Social12SignInResultESt8functionIFvS1_EEb
23:26:21 Error [MinecraftSymbols] Unresolved symbol: _ZN20MinecraftScreenModel11leaveScreenEv
23:26:21 Error [MinecraftSymbols] Unresolved symbol: _ZN6Social14MultiplayerXBLC2Ev
23:26:21 Error [MinecraftSymbols] Unresolved symbol: _ZTV22NullTextToSpeechClient
23:26:21 Error [MinecraftSymbols] Unresolved symbol: _ZNK7Options13getFullscreenEv
23:26:21 Error [MinecraftSymbols] Unresolved symbol: _ZN7Options13setFullscreenEb
23:26:21 Error [MinecraftSymbols] Unresolved symbol: _ZN15PermissionsFileC2ERKSs
23:26:21 Error [MinecraftSymbols] Unresolved symbol: _ZN19SkinPackKeyProviderC2Ev
23:26:21 Error [MinecraftSymbols] Unresolved symbol: _ZN19PackManifestFactoryC2ER14IPackTelemetry
23:26:21 Error [MinecraftSymbols] Unresolved symbol: _ZN17PackSourceFactoryC2Ev
23:26:21 Error [MinecraftSymbols] Unresolved symbol: _ZN22ResourcePackRepositoryC2ER18IMinecraftEventingR19PackManifestFactoryR29IContentAccessibilityProviderPN4Core15FilePathManagerER17PackSourceFactoryb
23:26:21 Error [MinecraftSymbols] Unresolved symbol: _ZN22ResourcePackRepository21addWorldResourcePacksERKN4Core4PathE
23:26:21 Error [MinecraftSymbols] Unresolved symbol: _ZN22ResourcePackRepository12refreshPacksEv
23:26:21 Error [MinecraftSymbols] Unresolved symbol: _ZN18ContentTierManagerC2Ev
23:26:21 Error [MinecraftSymbols] Unresolved symbol: _ZN19ResourcePackManagerC2ESt8functionIFN4Core10PathBufferISsEEvEERK18ContentTierManagerb
23:26:21 Error [MinecraftSymbols] Unresolved symbol: _ZN19ResourcePackManager8setStackESt10unique_ptrI17ResourcePackStackSt14default_deleteIS1_EE21ResourcePackStackTypeb
23:26:21 Error [MinecraftSymbols] Unresolved symbol: _ZN19ResourcePackManager17onLanguageChangedEv
23:26:21 Error [MinecraftSymbols] Unresolved symbol: _ZN12PackInstanceC2EP12ResourcePackibP12PackSettings
23:26:21 Error [MinecraftSymbols] Unresolved symbol: _ZTV17ResourcePackStack
23:26:21 Error [MinecraftSymbols] Unresolved symbol: _ZN17ResourcePackStack3addE12PackInstanceRK22ResourcePackRepositoryb
23:26:21 Error [MinecraftSymbols] Unresolved symbol: _ZN22SaveTransactionManagerC2ESt8functionIFvbEE
23:26:21 Error [MinecraftSymbols] Unresolved symbol: _ZN9Scheduler17processCoroutinesENSt6chrono8durationIxSt5ratioILx1ELx1000000000EEEE
23:26:21 Error [MinecraftSymbols] Unresolved symbol: _ZN18MinecraftScheduler6clientEv
23:26:21 Error [MinecraftSymbols] Unresolved symbol: _ZN19ServerCommandOriginC2ERKSsR11ServerLevel22CommandPermissionLevel
23:26:21 Error [MinecraftSymbols] Unresolved symbol: _ZN16EducationOptionsC2EP19ResourcePackManager
23:26:21 Error [MinecraftSymbols] Unresolved symbol: _ZN14ServerInstanceC2ER13IMinecraftAppR30ServerInstanceEventCoordinator
23:26:21 Error [MinecraftSymbols] Unresolved symbol: _ZN14ServerInstance16initializeServerER13IMinecraftAppR9WhitelistP15PermissionsFilePN4Core15FilePathManagerENSt6chrono8durationIxSt5ratioILx1ELx1EEEESsSsSs13LevelSettingsib20ConnectionDefinitionbRKSt6vectorISsSaISsEESsRKN3mce4UUIDER18IMinecraftEventingR22ResourcePackRepositoryRK18ContentTierManagerR19ResourcePackManagerSt8functionIFSt10unique_ptrI12LevelStorageSt14default_deleteIS10_EER9SchedulerEERKSsP9LevelDataSsSsSZ_I16EducationOptionsS11_IS1C_EEPSW_SY_IFvvEES1H_P13ServerMetricsP13DebugEndPointb
23:26:21 Error [MinecraftSymbols] Unresolved symbol: _ZN14ServerInstanceD2Ev
23:26:21 Error [MinecraftSymbols] Unresolved symbol: _ZN14ServerInstance17startServerThreadEv
23:26:21 Error [MinecraftSymbols] Unresolved symbol: _ZN14ServerInstance13leaveGameSyncEv
23:26:21 Error [MinecraftSymbols] Unresolved symbol: _ZN14ServerInstance20queueForServerThreadESt8functionIFvvEE
23:26:21 Error [MinecraftSymbols] Unresolved symbol: _ZN15SharedConstants12MajorVersionE
23:26:21 Error [MinecraftSymbols] Unresolved symbol: _ZN15SharedConstants12MinorVersionE
23:26:21 Error [MinecraftSymbols] Unresolved symbol: _ZN15SharedConstants12PatchVersionE
23:26:21 Error [MinecraftSymbols] Unresolved symbol: _ZN15SharedConstants15RevisionVersionE
23:26:21 Error [MinecraftSymbols] Unresolved symbol: _ZNK6Social4User11getLiveUserEv
23:26:21 Error [MinecraftSymbols] Unresolved symbol: _ZN6Social12XboxLiveUser22_handleUISignInNoErrorERN4xbox8services6system14sign_in_resultESt8functionIFvNS_12SignInResultEbEE
23:26:21 Error [MinecraftSymbols] Unresolved vtable symbol: _ZN9GameStore18onStoreInitializedEb
23:26:21 Error [MinecraftSymbols] Unresolved vtable symbol: _ZN9GameStore22onQueryProductsSuccessERKSt6vectorI11ProductInfoSaIS1_EE
23:26:21 Error [MinecraftSymbols] Unresolved symbol: _ZN6Social11UserManager17CreateUserManagerEv
23:26:21 Error [MinecraftSymbols] Unresolved symbol: _ZN2v82V810InitializeEv
23:26:21 Error [MinecraftSymbols] Unresolved symbol: _ZN2v82V818InitializePlatformEPNS_8PlatformE
23:26:21 Error [MinecraftSymbols] Unresolved symbol: _ZNK4pplx4taskIN4xbox8services16xbox_live_resultINS2_6system26token_and_signature_resultEEEE3getEv
23:26:21 Error [MinecraftSymbols] Unresolved symbol: _ZN2gl15getOpenGLVendorEv
23:26:21 Error [MinecraftSymbols] Unresolved symbol: _ZN2gl17getOpenGLRendererEv
23:26:21 Error [MinecraftSymbols] Unresolved symbol: _ZN2gl16getOpenGLVersionEv
23:26:21 Error [MinecraftSymbols] Unresolved symbol: _ZN2gl19getOpenGLExtensionsEv
23:26:21 Error [MinecraftSymbols] Unresolved symbol: _ZN3mce8Platform3OGL12InitBindingsEv
terminate called after throwing an instance of 'std::runtime_error'
  what():  Found no way to resolve library version, Minecraft version likely unsupported
Signal 6 received
Backtrace elements: 14
#0 /usr/bin/mcpelauncher-client(_ZN12CrashHandler12handleSignalEiPv+0xcc) [0x56662eec]
#1 linux-gate.so.1(__kernel_sigreturn+0) [0xf7ed5b60]
#2 linux-gate.so.1(__kernel_vsyscall+0x9) [0xf7ed5b49]
#3 /usr/lib32/libc.so.6(gsignal+0xc6) [0xf775f9b6]
#4 /usr/lib32/libc.so.6(abort+0x130) [0xf77483f5]
#5 /usr/lib32/libstdc++.so.6(+0x7593e) [0xf7a9893e]
#6 /usr/lib32/libstdc++.so.6(+0x83957) [0xf7aa6957]
#7 /usr/lib32/libstdc++.so.6(+0x839e3) [0xf7aa69e3]
#8 /usr/lib32/libstdc++.so.6(+0x83d25) [0xf7aa6d25]
#9 /usr/bin/mcpelauncher-client(+0x4e9d4) [0x566289d4]
#10 /usr/bin/mcpelauncher-client(_ZN16MinecraftVersion4initEv+0x2f) [0x56663ddf]
#11 /usr/bin/mcpelauncher-client(main+0xbbc) [0x5662c5ac]
#12 /usr/lib32/libc.so.6(__libc_start_main+0xf5) [0xf7749ee5]
#13 /usr/bin/mcpelauncher-client(_start+0x35) [0x5662de45]
Dumping stack...
#1 HYBRIS (null)+-274138400 in libminecraftpe.so+0x3a5bae0 [0xefa8fae0]
#5 HYBRIS (null)+-335331328 in libminecraftpe.so+0x0000 [0xec034000]
#24 HYBRIS void std::__detail::_Executor<__gnu_cxx::__normal_iterator<char const*, std::string>, std::allocator<std::sub_match<__gnu_cxx::__normal_iterator<char const*, std::string> > >, std::regex_traits<char>, true>::_M_dfs<false>(long)+12 in libminecraftpe.so+0xa0c29c [0xeca4029c]
#25 HYBRIS (null)+-274114224 in libminecraftpe.so+0x3a61950 [0xefa95950]
#26 HYBRIS (null)+-274114272 in libminecraftpe.so+0x3a61920 [0xefa95920]
#30 HYBRIS (null)+-274099152 in libminecraftpe.so+0x3a65430 [0xefa99430]
#31 HYBRIS (null)+-274102848 in libminecraftpe.so+0x3a645c0 [0xefa985c0]
#70 HYBRIS (null)+-274034512 in libminecraftpe.so+0x3a750b0 [0xefaa90b0]
#100 HYBRIS (null)+-273904464 in libminecraftpe.so+0x3a94cb0 [0xefac8cb0]
#101 HYBRIS (null)+-273908160 in libminecraftpe.so+0x3a93e40 [0xefac7e40]
#106 HYBRIS (null)+-273940477 in libminecraftpe.so+0x3a8c003 [0xefac0003]
#110 HYBRIS (null)+-273891664 in libminecraftpe.so+0x3a97eb0 [0xefacbeb0]
#111 HYBRIS (null)+-273893504 in libminecraftpe.so+0x3a97780 [0xefacb780]
#116 HYBRIS (null)+-324896980 in libminecraftpe.so+0x9f372c [0xeca2772c]
#119 HYBRIS (null)+-270196720 in libminecraftpe.so+0x3e1e010 [0xefe52010]
#120 HYBRIS std::string::_Rep::_S_empty_rep_storage+12 in libgnustl_shared.so+0x10cb84 [0xf363ab84]
#122 HYBRIS (null)+-213543032 in libminecraftpe.so+0x7425788 [0xf3459788]
#125 HYBRIS operator new(unsigned int)+12 in libgnustl_shared.so+0x506ac [0xf357e6ac]
#126 HYBRIS operator delete(void*)+6 in libgnustl_shared.so+0x4e086 [0xf357c086]
#127 HYBRIS (null)+-213543032 in libminecraftpe.so+0x7425788 [0xf3459788]
#128 HYBRIS (null)+-211599852 in libgnustl_shared.so+0x105e14 [0xf3633e14]
#130 HYBRIS std::string::_Rep::_S_empty_rep_storage+0 in libgnustl_shared.so+0x10cb78 [0xf363ab78]
#132 HYBRIS std::string::_Rep::_S_empty_rep_storage+12 in libgnustl_shared.so+0x10cb84 [0xf363ab84]
#134 HYBRIS (null)+-270196720 in libminecraftpe.so+0x3e1e010 [0xefe52010]
#135 HYBRIS std::string::_Rep::_S_empty_rep_storage+12 in libgnustl_shared.so+0x10cb84 [0xf363ab84]
#137 HYBRIS Core::FileStorageArea::sStorageAreas+0 in libminecraftpe.so+0x749e528 [0xf34d2528]
#138 HYBRIS (null)+-213543032 in libminecraftpe.so+0x7425788 [0xf3459788]
#140 HYBRIS Core::StorageAreasTree::insertStorageArea(Core::FileStorageArea&)+316 in libminecraftpe.so+0x3e0b50c [0xefe3f50c]
#145 HYBRIS (null)+-273865424 in libminecraftpe.so+0x3a9e530 [0xefad2530]
#150 HYBRIS (null)+-273863488 in libminecraftpe.so+0x3a9ecc0 [0xefad2cc0]
#151 HYBRIS (null)+-273865328 in libminecraftpe.so+0x3a9e590 [0xefad2590]
#155 HYBRIS std::string::_Rep::_S_empty_rep_storage+12 in libgnustl_shared.so+0x10cb84 [0xf363ab84]
#156 HYBRIS Core::Result::~Result()+9 in libminecraftpe.so+0x3e1d6b9 [0xefe516b9]
#158 HYBRIS (null)+-213543032 in libminecraftpe.so+0x7425788 [0xf3459788]
#159 HYBRIS std::string::_Rep::_S_empty_rep_storage+12 in libgnustl_shared.so+0x10cb84 [0xf363ab84]
#160 HYBRIS std::string::_Rep::_S_empty_rep_storage+12 in libgnustl_shared.so+0x10cb84 [0xf363ab84]
#161 HYBRIS std::string::_Rep::_S_empty_rep_storage+12 in libgnustl_shared.so+0x10cb84 [0xf363ab84]
#162 HYBRIS std::string::_Rep::_S_empty_rep_storage+12 in libgnustl_shared.so+0x10cb84 [0xf363ab84]
#163 HYBRIS std::string::_Rep::_S_empty_rep_storage+12 in libgnustl_shared.so+0x10cb84 [0xf363ab84]
#164 HYBRIS std::string::_Rep::_S_empty_rep_storage+12 in libgnustl_shared.so+0x10cb84 [0xf363ab84]
#165 HYBRIS std::string::_Rep::_S_empty_rep_storage+12 in libgnustl_shared.so+0x10cb84 [0xf363ab84]
#166 HYBRIS std::string::_Rep::_S_empty_rep_storage+12 in libgnustl_shared.so+0x10cb84 [0xf363ab84]
#167 HYBRIS std::string::_Rep::_S_empty_rep_storage+12 in libgnustl_shared.so+0x10cb84 [0xf363ab84]
#168 HYBRIS std::string::_Rep::_S_empty_rep_storage+12 in libgnustl_shared.so+0x10cb84 [0xf363ab84]
#169 HYBRIS std::string::_Rep::_S_empty_rep_storage+12 in libgnustl_shared.so+0x10cb84 [0xf363ab84]
#170 HYBRIS std::string::_Rep::_S_empty_rep_storage+12 in libgnustl_shared.so+0x10cb84 [0xf363ab84]
#171 HYBRIS std::string::_Rep::_S_empty_rep_storage+12 in libgnustl_shared.so+0x10cb84 [0xf363ab84]
#172 HYBRIS std::string::_Rep::_S_empty_rep_storage+12 in libgnustl_shared.so+0x10cb84 [0xf363ab84]
#173 HYBRIS std::string::_Rep::_S_empty_rep_storage+12 in libgnustl_shared.so+0x10cb84 [0xf363ab84]
#174 HYBRIS std::string::_Rep::_S_empty_rep_storage+12 in libgnustl_shared.so+0x10cb84 [0xf363ab84]
#175 HYBRIS std::string::_Rep::_S_empty_rep_storage+12 in libgnustl_shared.so+0x10cb84 [0xf363ab84]
#176 HYBRIS std::string::_Rep::_S_empty_rep_storage+12 in libgnustl_shared.so+0x10cb84 [0xf363ab84]
#177 HYBRIS std::string::_Rep::_S_empty_rep_storage+12 in libgnustl_shared.so+0x10cb84 [0xf363ab84]
#178 HYBRIS std::string::_Rep::_S_empty_rep_storage+12 in libgnustl_shared.so+0x10cb84 [0xf363ab84]
#179 HYBRIS std::string::_Rep::_S_empty_rep_storage+12 in libgnustl_shared.so+0x10cb84 [0xf363ab84]
#229 HYBRIS (null)+-212773224 in libminecraftpe.so+0x74e1698 [0xf3515698]
#237 HYBRIS (null)+-213581812 in libminecraftpe.so+0x741c00c [0xf345000c]
#630 HYBRIS vtable for xbox::services::local_config+0 in libminecraftpe.so+0x73eb778 [0xf341f778]
#631 HYBRIS vtable for xbox::services::local_config+8 in libminecraftpe.so+0x73eb780 [0xf341f780]
#651 HYBRIS (null)+-335331328 in libminecraftpe.so+0x0000 [0xec034000]
Process exited with unexpected exit code: 6

**Comment by ChristopherHX** [comment]
errorlog of minecraft-linux legacy master.
This master cannot create that error, you probably haven't installed it correctly.
**I recommend using the appimage**
