### ISSUE TITLE
Exited with error code 4

### ISSUE THREAD

**Issue by Godolt** [ChristopherHX/mcpelauncher-manifest#82]
Using manjaro linux.
[crashlog.txt](https://github.com/ChristopherHX/mcpelauncher-manifest/files/4572424/crashlog.txt)

**Comment by ChristopherHX** [comment]
**Your very old amd cpu is unsupported**
Your CPU amd 2011 seems to haven't the instruction set **SSSE3** (I looked it up, amd added it ca. 2012, after intel ca. 2008), but the game and Android **require it** for intel / amd.

Exited with error code 4 means illegal instruction after Minecraft used a SSSE3 command, which your pc doesn't understand
