### ISSUE TITLE
Process exited with unexpected exit code: 4 (Any 64bit version)

### ISSUE THREAD

**Issue by PacketCat** [ChristopherHX/mcpelauncher-manifest#85]
21:43:13 Info  [Launcher] Version: client e3958c2 / manifest 4138b9a
21:43:13 Info  [Launcher] CPU: GenuineIntel Intel(R) Core(TM)2 Duo CPU     T5270  @ 1.40GHz
21:43:13 Info  [Launcher] CPU supports SSSE3: YES
21:43:13 Trace [Launcher] Loading hybris libraries
21:43:13 Trace [HybrisUtils] Loaded OS library libm.so.6
load_library: Undefined symbol gamma_r
load_library: Undefined symbol gammaf_r
21:43:13 Trace [HybrisUtils] Loaded OS library libz.so.1
21:43:13 Trace [HybrisUtils] Loaded OS library /tmp/.mount_MinecrodqU28/usr/share/mcpelauncher/lib/native/x86_64/libfmod.so.12.0
load_library: Undefined symbol _ZN4FMOD14ChannelControl15set3DAttributesEPK11FMOD_VECTORS3_S3_
21:43:13 Trace [Launcher] Loading Minecraft library
linker: dlopen(name="libminecraftpe.so", flags=0x0, extinfo=(null), caller="(null)", caller_ns=@0xb68ff8, targetSdkVersion=10000) ...
linker: find_libraries(ns=): task=libminecraftpe.so, is_dt_needed=0
linker: load_library(ns=, task=libminecraftpe.so, flags=0x0, search_linked_namespaces=1): calling open_library with realpath=
linker: load_library(ns=, task=libminecraftpe.so, flags=0x0, realpath=/home/kotb/.local/share/mcpelauncher/versions/1.16.0.59/lib/x86_64/libminecraftpe.so, search_linked_namespaces=1)
linker: load_library(ns=, task=libminecraftpe.so): Adding DT_NEEDED task: libfmod.so
linker: load_library(ns=, task=libminecraftpe.so): Adding DT_NEEDED task: libc++_shared.so
linker: load_library(ns=, task=libminecraftpe.so): Adding DT_NEEDED task: liblog.so
linker: load_library(ns=, task=libminecraftpe.so): Adding DT_NEEDED task: libandroid.so
linker: load_library(ns=, task=libminecraftpe.so): Adding DT_NEEDED task: libEGL.so
linker: load_library(ns=, task=libminecraftpe.so): Adding DT_NEEDED task: libOpenSLES.so
linker: load_library(ns=, task=libminecraftpe.so): Adding DT_NEEDED task: libm.so
linker: load_library(ns=, task=libminecraftpe.so): Adding DT_NEEDED task: libdl.so
linker: load_library(ns=, task=libminecraftpe.so): Adding DT_NEEDED task: libc.so
linker: find_libraries(ns=): task=libfmod.so, is_dt_needed=1
linker: find_library_internal(ns=, task=libfmod.so): Already loaded (by soname): libfmod.so
linker: find_libraries(ns=): task=libc++_shared.so, is_dt_needed=1
linker: load_library(ns=, task=libc++_shared.so, flags=0x0, search_linked_namespaces=1): calling open_library with realpath=
linker: load_library(ns=, task=libc++_shared.so, flags=0x0, realpath=/home/kotb/.local/share/mcpelauncher/versions/1.16.0.59/lib/x86_64/libc++_shared.so, search_linked_namespaces=1)
linker: load_library(ns=, task=libc++_shared.so): Adding DT_NEEDED task: libc.so
linker: load_library(ns=, task=libc++_shared.so): Adding DT_NEEDED task: libdl.so
linker: find_libraries(ns=): task=liblog.so, is_dt_needed=1
linker: find_library_internal(ns=, task=liblog.so): Already loaded (by soname): liblog.so
linker: find_libraries(ns=): task=libandroid.so, is_dt_needed=1
linker: find_library_internal(ns=, task=libandroid.so): Already loaded (by soname): libandroid.so
linker: find_libraries(ns=): task=libEGL.so, is_dt_needed=1
linker: find_library_internal(ns=, task=libEGL.so): Already loaded (by soname): libEGL.so
linker: find_libraries(ns=): task=libOpenSLES.so, is_dt_needed=1
linker: find_library_internal(ns=, task=libOpenSLES.so): Already loaded (by soname): libOpenSLES.so
linker: find_libraries(ns=): task=libm.so, is_dt_needed=1
linker: find_library_internal(ns=, task=libm.so): Already loaded (by soname): libm.so
linker: find_libraries(ns=): task=libdl.so, is_dt_needed=1
linker: find_library_internal(ns=, task=libdl.so): Already loaded (by soname): libdl.so
linker: find_libraries(ns=): task=libc.so, is_dt_needed=1
linker: find_library_internal(ns=, task=libc.so): Already loaded (by soname): libc.so
linker: find_libraries(ns=): task=libc.so, is_dt_needed=1
linker: find_library_internal(ns=, task=libc.so): Already loaded (by soname): libc.so
linker: find_libraries(ns=): task=libdl.so, is_dt_needed=1
linker: find_library_internal(ns=, task=libdl.so): Already loaded (by soname): libdl.so
linker: ... dlopen calling constructors: realpath="/home/kotb/.local/share/mcpelauncher/versions/1.16.0.59/lib/x86_64/libminecraftpe.so", soname="libminecraftpe.so", handle=0x23
Process exited with unexpected exit code: 4

**Comment by ChristopherHX** [comment]
Your Operating System is?
Is your PC cappable for running Android 5+ x86_64? 
Exit code 4 means invalid instruction, might be a Launcher or cpu error
I'm not shure about that
I only tested a i5 Ivy bridge and newer i7 both don't crash there. (I don't own older x64 cpus)

**Comment by PacketCat** [comment]
Lubuntu 20.04

**Comment by PacketCat** [comment]
My CPU is Core 2 Duo, and i think its can run android 5+ x86_64

**Comment by ChristopherHX** [comment]
**No you cannot run Android x86_64 nor Minecraft in 64 bit**
You have
Under Extensions and Technologies
http://www.cpu-world.com/CPUs/Core_2/Intel-Core%202%20Duo%20Mobile%20T5270%20LF80537GG0172M.html
Minecraft and Android x86_64 needs
https://developer.android.com/ndk/guides/abis#86-64
**Your PC is missing SSE4.1, 4.2 and POPCNT**
You can keep using 32bit versions, but you need a new CPU for 64bit Bedrock

**Comment by PacketCat** [comment]
Okay, thanks for explaining
