### ISSUE TITLE
Exit code: 127, I ran the commands needed to fix this. Yet nothing fixed it.

### ISSUE THREAD

**Issue by A-Random-Lantern** [ChristopherHX/mcpelauncher-manifest#86]
/tmp/.mount_Minecrkk5yIr/usr/bin/./mcpelauncher-client32: error while loading shared libraries: libEGL.so.1: cannot open shared object file: No such file or directory
Process exited with unexpected exit code: 127

**Comment by ChristopherHX** [comment]
You have two choices
- Logout and login from google play again to enable 64bit versions and select one (64bit) in the Profile editor (64bit don't need 32bit libraries, you haven't installed)
- Read the instruction of the stable appimage  https://github.com/ChristopherHX/linux-packaging-scripts/releases/tag/appimage
**You should currently prefer that over the Test Release**

**Comment by A-Random-Lantern** [comment]
Hm, none of those work. Same problem

**Comment by ChristopherHX** [comment]
Is it impossible to install?
Idk what you tried or not after running these commands libEGL.so.1 should be installed
For **Debian** install `sudo dpkg --add-architecture i386 && (sudo apt-get update || :) && sudo apt install libc6-i386 libx11-6:i386 libegl1-mesa:i386 zlib1g:i386 libstdc++6:i386 libgl1-mesa-dri:i386 libasound2:i386 pulseaudio`
For **archlinux** enable [Multilib](https://wiki.archlinux.org/index.php/Official_repositories#multilib) then install `sudo pacman -Sy && sudo pacman -S lib32-mesa lib32-libpulse lib32-alsa-plugins` 
For **Fedora** https://github.com/ChristopherHX/linux-packaging-scripts/commit/789da63c22e14c4279ebbd046717070c327e1db1#commitcomment-38676429
for other distro figure it out
For **Void Linux** 
`sudo xbps-install void-repo-multilib`
after that
`sudo xbps-install -S`
to sync repos, then
`sudo xbps-install mesa-32bit mesa-dri-32bit libcurl-32bit libpng-32bit libX11-32bit libgcc-32bit libstdc++-32bit glibc-32bit libgudev-32bit libXi-32bit alsa-lib-32bit libpulseaudio-32bit`
on 64bit systems
For **Solus** install `sudo eopkg install mesalib-32bit openssl-32bit curl-32bit libpng-32bit libx11-32bit libgcc-32bit libstdc++-32bit glibc-32bit libgudev-32bit libxi-32bit`

**Comment by ChristopherHX** [comment]
Idk, if you can say same problem,
if the error text changed one character it isn't the same error.
You would be the first one who get your error above after installing all dependencies.
