### ISSUE TITLE
Cannot exit out of Minecraft normally

### ISSUE THREAD

**Issue by TechnologyMan101** [ChristopherHX/mcpelauncher-manifest#87]
Trying to leave Minecraft results in the game window hanging. Have to force close through the launcher.

Using AppImage on Pop!_OS 20.04 LTS

Minecraft 1.14.60.5 (64-bit)

**Comment by ChristopherHX** [comment]
> Using AppImage on Pop!_OS 20.04 LTS
Minecraft 1.14.60.5 (64-bit)

You are on a unsupported Test Release, Minecraft 1.14.60.5 (64-bit) isn't supported in the stable version at all.
You find the stable one here: https://github.com/ChristopherHX/linux-packaging-scripts/releases/tag/appimage
It supports only Minecraft 1.14.60.5 (32-bit) and doesn't crash on exit

**Comment by TechnologyMan101** [comment]
Thank you! I didn't realize that the game version was a test release as it was the default.
