### ISSUE TITLE
Sign in with Microsoft account doesn’t work in build for Catalina

### ISSUE THREAD

**Issue by Semper-Viventem** [ChristopherHX/mcpelauncher-manifest#90]
Hey @ChristopherHX

Thank you for your support and app updates. I Tried version for macOS Catalina from [this](https://github.com/ChristopherHX/mcpelauncher-manifest/issues/28#issuecomment-628924261) comment. It's working, but I can't sign in Microsoft Account. It opens WebView, then I log in and nothing happens :(

Thanks!

**Comment by ChristopherHX** [comment]
Do you have a xbox live profile for your MS account?
This launcher is unable to create one for you,
please login to a official client once (or create one at http://xbox.com)

Or Network issues (e.g. only internet access via a proxy).

Maybe try again, to make shure it wasn't a temporary problem. (if the game shows a login box for more than a minute it failed silently in the background, then close the game and try again)

Xbox live login have known stability problems. (all versions)

**Comment by Semper-Viventem** [comment]
Thanks. The problem was with my Microsoft account auth settings: I didn't can sign in and didn't see any error messages. But launcher works correctly. I'll close this issue
