### ISSUE TITLE
Client don't saves any changes in settings (ng)

### ISSUE THREAD

**Issue by PacketCat** [ChristopherHX/mcpelauncher-manifest#91]
When you changing anything in settings(or picking skin) its saves only for that session. After reboot nothing from last session not saved.
Im tried:
- reinstall appimage
- delete /home/user/.local/share/mcpelauncher folder
- change data directory in profile
Nothing of this doesn't working

(Also sorry for my English, my main language is Russian)

**Comment by ChristopherHX** [comment]
ng literally reopen all closed issues #21
mrarm wanted to do it from 'scratch'.
0.14 is totally unplayable on ng, because of that.
