### ISSUE TITLE
Controller For mac version

### ISSUE THREAD

**Issue by ElijahTaylorHolland** [ChristopherHX/mcpelauncher-manifest#93]
Hey man i love what you've done here but is there anyway you can tell me how to connect a controller for mac? when i plug in an xbox or ps4 controller it crashes.

**Comment by ChristopherHX** [comment]
You are using with launcher (experimental for 10.10+ / 10.15+ may crash)

**Comment by ChristopherHX** [comment]
Please provide crash log via pastebin or similar

**Comment by ChristopherHX** [comment]
> Please provide crash log via pastebin or similar
Not happend after 2 weeks, reopen it with more information if you want this fixed
